package com.syncari.core.model.insights.provider.ts;

public enum TSPrivileges {
    ADMINISTRATION,DEVELOPER,AUTHORING,USERDATAUPLOADING,DATADOWNLOADING,USERMANAGEMENT,DATAMANAGEMENT,SHAREWITHALL,
    JOBSCHEDULING,RANALYSIS,A3ANALYSIS,BYPASSRLS,PREVIEW_THOUGHTSPOT_SAGE,NONE;
}
