import { PipelinePickerValue } from './PipelinePicker';
import { PipelinePickerEntity } from './PipelinePicker.types';

export const pipelineSchemas: PipelinePickerEntity[] = [
  {
    apiName: 'account',
    id: '60e49df87c987b42ccd83c0e',
    displayName: 'Account',
    fields: [
      {
        id: '60e49df87c987b42ccd83c17',
        apiName: 'AboutUs',
        displayName: 'About Us',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c2c',
        apiName: 'Description',
        displayName: 'Account Description',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c16',
        apiName: 'Id',
        displayName: 'Account ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83c1a',
        apiName: 'Name',
        displayName: 'Account Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c27',
        apiName: 'Phone',
        displayName: 'Account Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c36',
        apiName: 'AccountSource',
        displayName: 'Account Source',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c1b',
        apiName: 'Type',
        displayName: 'Account Type',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c3e',
        apiName: 'AnnualRevenue',
        displayName: 'Annual Revenue',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83c1e',
        apiName: 'BillingCity',
        displayName: 'Billing City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c21',
        apiName: 'BillingCountry',
        displayName: 'Billing Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c1f',
        apiName: 'BillingState',
        displayName: 'Billing State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c1d',
        apiName: 'BillingStreet',
        displayName: 'Billing Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c20',
        apiName: 'BillingPostalCode',
        displayName: 'Billing Zip/Postal Code',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c3c',
        apiName: 'CloseDate',
        displayName: 'Close Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c2f',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c2e',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c18',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c3d',
        apiName: 'Domain',
        displayName: 'Domain',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c2b',
        apiName: 'NumberOfEmployees',
        displayName: 'Employees',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83c2a',
        apiName: 'Industry',
        displayName: 'Industry',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c38',
        apiName: 'IsPublic',
        displayName: 'Is Public',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c31',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c30',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c19',
        apiName: 'MasterRecordId',
        displayName: 'Master Record ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c2d',
        apiName: 'OwnerId',
        displayName: 'Owner ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c1c',
        apiName: 'ParentId',
        displayName: 'Parent Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c29',
        apiName: 'PhotoUrl',
        displayName: 'Photo URL',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c3b',
        apiName: 'Score',
        displayName: 'Score',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83c23',
        apiName: 'ShippingCity',
        displayName: 'Shipping City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c26',
        apiName: 'ShippingCountry',
        displayName: 'Shipping Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c24',
        apiName: 'ShippingState',
        displayName: 'Shipping State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c22',
        apiName: 'ShippingStreet',
        displayName: 'Shipping Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c25',
        apiName: 'ShippingPostalCode',
        displayName: 'Shipping Zip/Postal Code',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c32',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c39',
        apiName: 'TotalMoneyRaised',
        displayName: 'Total Money Raised',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c3a',
        apiName: 'TwitterHandle',
        displayName: 'Twitter Handle',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c28',
        apiName: 'Website',
        displayName: 'Website',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c37',
        apiName: 'YearStarted',
        displayName: 'Year Started',
        dataType: 'string',
      },
    ],
  },
  {
    apiName: 'activity',
    id: '60e49df87c987b42ccd83c13',
    displayName: 'Activity',
    fields: [
      {
        id: '60e49df87c987b42ccd83d11',
        apiName: 'AccountId',
        displayName: 'Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d10',
        apiName: 'Id',
        displayName: 'Activity ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83d2f',
        apiName: 'ActivitySubtype',
        displayName: 'Activity Subtype',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83d1c',
        apiName: 'IsAllDayEvent',
        displayName: 'All-Day Event',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d27',
        apiName: 'CallDurationInSeconds',
        displayName: 'Call Duration',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83d2a',
        apiName: 'CallObject',
        displayName: 'Call Object Identifier',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d29',
        apiName: 'CallDisposition',
        displayName: 'Call Result',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d28',
        apiName: 'CallType',
        displayName: 'Call Type',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83d1b',
        apiName: 'IsClosed',
        displayName: 'Closed',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d20',
        apiName: 'Description',
        displayName: 'Comments',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83d23',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d22',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d16',
        apiName: 'ActivityDate',
        displayName: 'Date',
        dataType: 'date',
      },
      {
        id: '60e49df87c987b42ccd83d21',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d1e',
        apiName: 'DurationInMinutes',
        displayName: 'Duration',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83d2d',
        apiName: 'EndDateTime',
        displayName: 'End',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d19',
        apiName: 'IsHighPriority',
        displayName: 'High Priority',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d25',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d24',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d1f',
        apiName: 'Location',
        displayName: 'Location',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d12',
        apiName: 'WhoId',
        displayName: 'Name ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d18',
        apiName: 'Priority',
        displayName: 'Priority',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83d1d',
        apiName: 'IsVisibleInSelfService',
        displayName: 'Public',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d13',
        apiName: 'WhatId',
        displayName: 'Related To ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d2b',
        apiName: 'ReminderDateTime',
        displayName: 'Reminder Date/Time',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d2c',
        apiName: 'IsReminderSet',
        displayName: 'Reminder Set',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d2e',
        apiName: 'StartDateTime',
        displayName: 'Start',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d17',
        apiName: 'Status',
        displayName: 'Status',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83d14',
        apiName: 'Subject',
        displayName: 'Subject',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d26',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83d15',
        apiName: 'IsTask',
        displayName: 'Task',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d1a',
        apiName: 'ActivityType',
        displayName: 'Type',
        dataType: 'picklist',
      },
    ],
  },
  {
    apiName: 'contact',
    id: '60e49df87c987b42ccd83c0f',
    displayName: 'Contact',
    fields: [
      {
        id: '60e49df87c987b42ccd83c43',
        apiName: 'AccountId',
        displayName: 'Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c52',
        apiName: 'Phone',
        displayName: 'Business Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c49',
        apiName: 'City',
        displayName: 'City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c40',
        apiName: 'Id',
        displayName: 'Contact ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83c4c',
        apiName: 'Country',
        displayName: 'Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c59',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c58',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c66',
        apiName: 'Jigsaw',
        displayName: 'Data.com Key',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c41',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c56',
        apiName: 'Department',
        displayName: 'Department',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c54',
        apiName: 'Email',
        displayName: 'Email',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c63',
        apiName: 'EmailBouncedDate',
        displayName: 'Email Bounced Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c62',
        apiName: 'EmailBouncedReason',
        displayName: 'Email Bounced Reason',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c68',
        apiName: 'HasOptedOutOfEmail',
        displayName: 'Email Opt Out',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c45',
        apiName: 'FirstName',
        displayName: 'First Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c47',
        apiName: 'Name',
        displayName: 'Full Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c64',
        apiName: 'IsEmailBounced',
        displayName: 'Is Email Bounced',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c67',
        apiName: 'JigsawContactId',
        displayName: 'Jigsaw Contact ID',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c5b',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c5a',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c44',
        apiName: 'LastName',
        displayName: 'Last Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c5e',
        apiName: 'LastCURequestDate',
        displayName: 'Last Stay-in-Touch Request Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c5f',
        apiName: 'LastCUUpdateDate',
        displayName: 'Last Stay-in-Touch Save Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c4e',
        apiName: 'MailingCity',
        displayName: 'Mailing City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c51',
        apiName: 'MailingCountry',
        displayName: 'Mailing Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c4f',
        apiName: 'MailingState',
        displayName: 'Mailing State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c4d',
        apiName: 'MailingStreet',
        displayName: 'Mailing Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c50',
        apiName: 'MailingPostalCode',
        displayName: 'Mailing Zip/Postal Code',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c42',
        apiName: 'MasterRecordId',
        displayName: 'Master Record ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c53',
        apiName: 'MobilePhone',
        displayName: 'Mobile Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c57',
        apiName: 'OwnerId',
        displayName: 'Owner ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c65',
        apiName: 'PhotoUrl',
        displayName: 'Photo URL',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c46',
        apiName: 'Salutation',
        displayName: 'Salutation',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c4a',
        apiName: 'State',
        displayName: 'State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c48',
        apiName: 'Street',
        displayName: 'Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c5c',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c55',
        apiName: 'Title',
        displayName: 'Title',
        dataType: 'string',
      },
      {
        id: '60e4cac2532a1b566b936220',
        apiName: 'User_Lookup_One__c',
        displayName: 'User Lookup One',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c4b',
        apiName: 'PostalCode',
        displayName: 'Zip/Postal Code',
        dataType: 'string',
      },
    ],
  },
  {
    apiName: 'lead',
    id: '60e49df87c987b42ccd83c10',
    displayName: 'Lead',
    fields: [
      {
        id: '60e49df87c987b42ccd83c74',
        apiName: 'City',
        displayName: 'City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c72',
        apiName: 'Company',
        displayName: 'Company',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c85',
        apiName: 'IsConverted',
        displayName: 'Converted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c87',
        apiName: 'ConvertedAccountId',
        displayName: 'Converted Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c88',
        apiName: 'ConvertedContactId',
        displayName: 'Converted Contact ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c86',
        apiName: 'ConvertedDate',
        displayName: 'Converted Date',
        dataType: 'date',
      },
      {
        id: '60e49df87c987b42ccd83c89',
        apiName: 'ConvertedOpportunityId',
        displayName: 'Converted Opportunity ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c77',
        apiName: 'Country',
        displayName: 'Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c8c',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c8b',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c93',
        apiName: 'Jigsaw',
        displayName: 'Data.com Key',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c6b',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c80',
        apiName: 'Description',
        displayName: 'Description',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c7d',
        apiName: 'Email',
        displayName: 'Email',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c96',
        apiName: 'EmailBouncedDate',
        displayName: 'Email Bounced Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c95',
        apiName: 'EmailBouncedReason',
        displayName: 'Email Bounced Reason',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c83',
        apiName: 'NumberOfEmployees',
        displayName: 'Employees',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83c6e',
        apiName: 'FirstName',
        displayName: 'First Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c70',
        apiName: 'Name',
        displayName: 'Full Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c7a',
        apiName: 'GeocodeAccuracy',
        displayName: 'Geocode Accuracy',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c82',
        apiName: 'Industry',
        displayName: 'Industry',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c94',
        apiName: 'JigsawContactId',
        displayName: 'Jigsaw Contact ID',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c8e',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c8d',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c6d',
        apiName: 'LastName',
        displayName: 'Last Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c78',
        apiName: 'Latitude',
        displayName: 'Latitude',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83c6a',
        apiName: 'Id',
        displayName: 'Lead ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83c79',
        apiName: 'Longitude',
        displayName: 'Longitude',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83c6c',
        apiName: 'MasterRecordId',
        displayName: 'Master Record ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c7c',
        apiName: 'MobilePhone',
        displayName: 'Mobile Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c84',
        apiName: 'OwnerId',
        displayName: 'Owner ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c7b',
        apiName: 'Phone',
        displayName: 'Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c7f',
        apiName: 'PhotoUrl',
        displayName: 'Photo URL',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c6f',
        apiName: 'Salutation',
        displayName: 'Salutation',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c75',
        apiName: 'State',
        displayName: 'State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c81',
        apiName: 'Status',
        displayName: 'Status',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c73',
        apiName: 'Street',
        displayName: 'Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83c8f',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c71',
        apiName: 'Title',
        displayName: 'Title',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c8a',
        apiName: 'IsUnreadByOwner',
        displayName: 'Unread By Owner',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83c7e',
        apiName: 'Website',
        displayName: 'Website',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c76',
        apiName: 'PostalCode',
        displayName: 'Zip/Postal Code',
        dataType: 'string',
      },
    ],
  },
  {
    apiName: 'opportunity',
    id: '60e49df87c987b42ccd83c11',
    displayName: 'Opportunity',
    fields: [
      {
        id: '60e49df87c987b42ccd83cd3',
        apiName: 'AccountId',
        displayName: 'Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cd7',
        apiName: 'Amount',
        displayName: 'Amount',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83cd9',
        apiName: 'CloseDate',
        displayName: 'Close Date',
        dataType: 'date',
      },
      {
        id: '60e49df87c987b42ccd83cdc',
        apiName: 'IsClosed',
        displayName: 'Closed',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ce3',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83ce2',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cd2',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83cd5',
        apiName: 'Description',
        displayName: 'Description',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cea',
        apiName: 'Fiscal',
        displayName: 'Fiscal Period',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ce8',
        apiName: 'FiscalQuarter',
        displayName: 'Fiscal Quarter',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83ce9',
        apiName: 'FiscalYear',
        displayName: 'Fiscal Year',
        dataType: 'integer',
      },
      {
        id: '60e49df87c987b42ccd83cde',
        apiName: 'ForecastCategory',
        displayName: 'Forecast Category',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cdf',
        apiName: 'ForecastCategoryName',
        displayName: 'Forecast Category',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83ce0',
        apiName: 'HasOpportunityLineItem',
        displayName: 'Has Line Item',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ced',
        apiName: 'HasOpenActivity',
        displayName: 'Has Open Activity',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83cee',
        apiName: 'HasOverdueTask',
        displayName: 'Has Overdue Task',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ce5',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ce4',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cd4',
        apiName: 'Name',
        displayName: 'Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cdb',
        apiName: 'NextStep',
        displayName: 'Next Step',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cd1',
        apiName: 'Id',
        displayName: 'Opportunity ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83cda',
        apiName: 'Type',
        displayName: 'Opportunity Type',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83ce1',
        apiName: 'OwnerId',
        displayName: 'Owner ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cd8',
        apiName: 'Probability',
        displayName: 'Probability (%)',
        dataType: 'double',
      },
      {
        id: '60e49df87c987b42ccd83cd6',
        apiName: 'StageName',
        displayName: 'Stage',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83ce6',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cdd',
        apiName: 'IsWon',
        displayName: 'Won',
        dataType: 'boolean',
      },
    ],
  },
  {
    apiName: 'ticket',
    id: '60e49df87c987b42ccd83c12',
    displayName: 'Ticket',
    fields: [
      {
        id: '60e49df87c987b42ccd83cf4',
        apiName: 'AccountId',
        displayName: 'Account ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cf0',
        apiName: 'Id',
        displayName: 'Case ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83cfd',
        apiName: 'Origin',
        displayName: 'Case Origin',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cfc',
        apiName: 'Reason',
        displayName: 'Case Reason',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cfa',
        apiName: 'Type',
        displayName: 'Case Type',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83d01',
        apiName: 'IsClosed',
        displayName: 'Closed',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d02',
        apiName: 'ClosedDate',
        displayName: 'Closed Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cf9',
        apiName: 'SuppliedCompany',
        displayName: 'Company',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d0b',
        apiName: 'ContactEmail',
        displayName: 'Contact Email',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cf3',
        apiName: 'ContactId',
        displayName: 'Contact ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d0a',
        apiName: 'ContactMobile',
        displayName: 'Contact Mobile',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d09',
        apiName: 'ContactPhone',
        displayName: 'Contact Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d05',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d04',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cf1',
        apiName: 'IsDeleted',
        displayName: 'Deleted',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d00',
        apiName: 'Description',
        displayName: 'Description',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cf7',
        apiName: 'SuppliedEmail',
        displayName: 'Email Address',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d03',
        apiName: 'IsEscalated',
        displayName: 'Escalated',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83d0c',
        apiName: 'Comments',
        displayName: 'Internal Comments',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83d07',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83d06',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cf6',
        apiName: 'SuppliedName',
        displayName: 'Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cf5',
        apiName: 'ParentId',
        displayName: 'Parent Ticket ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cf8',
        apiName: 'SuppliedPhone',
        displayName: 'Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cff',
        apiName: 'Priority',
        displayName: 'Priority',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cfb',
        apiName: 'Status',
        displayName: 'Status',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cfe',
        apiName: 'Subject',
        displayName: 'Subject',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83d08',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cf2',
        apiName: 'CaseNumber',
        displayName: 'Ticket Number',
        dataType: 'string',
      },
    ],
  },
  {
    apiName: 'user',
    id: '60e49df87c987b42ccd83c14',
    displayName: 'User',
    fields: [
      {
        id: '60e49df87c987b42ccd83ccb',
        apiName: 'AboutMe',
        displayName: 'About Me',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cb5',
        apiName: 'IsActive',
        displayName: 'Active',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83cb9',
        apiName: 'ReceivesAdminInfoEmails',
        displayName: 'Admin Info Emails',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83cb2',
        apiName: 'Alias',
        displayName: 'Alias',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ca7',
        apiName: 'EmailPreferencesAutoBcc',
        displayName: 'AutoBcc',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ca8',
        apiName: 'EmailPreferencesAutoBccStayInTouch',
        displayName: 'AutoBccStayInTouch',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ca2',
        apiName: 'City',
        displayName: 'City',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c9d',
        apiName: 'CompanyName',
        displayName: 'Company Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cc7',
        apiName: 'ContactId',
        displayName: 'Contact ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83ca5',
        apiName: 'Country',
        displayName: 'Country',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cc3',
        apiName: 'CreatedById',
        displayName: 'Created By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cc2',
        apiName: 'CreatedDate',
        displayName: 'Created Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cbe',
        apiName: 'DelegatedApproverId',
        displayName: 'Delegated Approver ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83c9f',
        apiName: 'Department',
        displayName: 'Department',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c9e',
        apiName: 'Division',
        displayName: 'Division',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ca6',
        apiName: 'Email',
        displayName: 'Email',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cba',
        apiName: 'EmailEncodingKey',
        displayName: 'Email Encoding',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83caa',
        apiName: 'SenderEmail',
        displayName: 'Email Sender Address',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cab',
        apiName: 'SenderName',
        displayName: 'Email Sender Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cac',
        apiName: 'Signature',
        displayName: 'Email Signature',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cbd',
        apiName: 'EmployeeNumber',
        displayName: 'Employee Number',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cc9',
        apiName: 'Extension',
        displayName: 'Extension',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c9b',
        apiName: 'FirstName',
        displayName: 'First Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83c9c',
        apiName: 'Name',
        displayName: 'Full Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cb8',
        apiName: 'ReceivesInfoEmails',
        displayName: 'Info Emails',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83cbc',
        apiName: 'LanguageLocaleKey',
        displayName: 'Language',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cc0',
        apiName: 'LastLoginDate',
        displayName: 'Last Login',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cc5',
        apiName: 'LastModifiedById',
        displayName: 'Last Modified By ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cc4',
        apiName: 'LastModifiedDate',
        displayName: 'Last Modified Date',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83c9a',
        apiName: 'LastName',
        displayName: 'Last Name',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cc1',
        apiName: 'LastPasswordChangeDate',
        displayName: 'Last Password Change or Reset',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cb7',
        apiName: 'LocaleSidKey',
        displayName: 'Locale',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83cbf',
        apiName: 'ManagerId',
        displayName: 'Manager ID',
        dataType: 'reference',
      },
      {
        id: '60e49df87c987b42ccd83cb1',
        apiName: 'MobilePhone',
        displayName: 'Mobile',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cb3',
        apiName: 'CommunityNickname',
        displayName: 'Nickname',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cb0',
        apiName: 'Phone',
        displayName: 'Phone',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cca',
        apiName: 'FederationIdentifier',
        displayName: 'SAML Federation ID',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ccd',
        apiName: 'IsExtIndicatorVisible',
        displayName: 'Show external indicator',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ca3',
        apiName: 'State',
        displayName: 'State/Province',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83caf',
        apiName: 'StayInTouchNote',
        displayName: 'Stay-in-Touch Email Note',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cae',
        apiName: 'StayInTouchSignature',
        displayName: 'Stay-in-Touch Email Signature',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cad',
        apiName: 'StayInTouchSubject',
        displayName: 'Stay-in-Touch Email Subject',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ca9',
        apiName: 'EmailPreferencesStayInTouchReminder',
        displayName: 'StayInTouchReminder',
        dataType: 'boolean',
      },
      {
        id: '60e49df87c987b42ccd83ca1',
        apiName: 'Street',
        displayName: 'Street',
        dataType: 'textarea',
      },
      {
        id: '60e49df87c987b42ccd83cc6',
        apiName: 'SystemModstamp',
        displayName: 'System Modstamp',
        dataType: 'datetime',
      },
      {
        id: '60e49df87c987b42ccd83cb6',
        apiName: 'TimeZoneSidKey',
        displayName: 'Time Zone',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83ca0',
        apiName: 'Title',
        displayName: 'Title',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ccc',
        apiName: 'FullPhotoUrl',
        displayName: 'Url for full-sized Photo',
        dataType: 'url',
      },
      {
        id: '60e49df87c987b42ccd83c98',
        apiName: 'Id',
        displayName: 'User ID',
        dataType: 'id',
      },
      {
        id: '60e49df87c987b42ccd83cb4',
        apiName: 'BadgeText',
        displayName: 'User Photo badge text overlay',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83cbb',
        apiName: 'UserType',
        displayName: 'User Type',
        dataType: 'picklist',
      },
      {
        id: '60e49df87c987b42ccd83c99',
        apiName: 'Username',
        displayName: 'Username',
        dataType: 'string',
      },
      {
        id: '60e49df87c987b42ccd83ca4',
        apiName: 'PostalCode',
        displayName: 'Zip/Postal Code',
        dataType: 'string',
      },
    ],
  },
];

export const pipelinePickerEntityValue: PipelinePickerValue = {
  entities: [
    {
      id: '60e49df87c987b42ccd83c0f',
      apiName: 'contact',
      displayName: 'Contact',
      fields: [
        {
          id: '60e49df87c987b42ccd83c43',
          apiName: 'AccountId',
          displayName: 'Account ID',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83c52',
          apiName: 'Phone',
          displayName: 'Business Phone',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c40',
          apiName: 'Id',
          displayName: 'Contact ID',
          dataType: 'id',
        },
        {
          id: '60e49df87c987b42ccd83c4c',
          apiName: 'Country',
          displayName: 'Country',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c66',
          apiName: 'Jigsaw',
          displayName: 'Data.com Key',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c41',
          apiName: 'IsDeleted',
          displayName: 'Deleted',
          dataType: 'boolean',
        },
        {
          id: '60e49df87c987b42ccd83c56',
          apiName: 'Department',
          displayName: 'Department',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c54',
          apiName: 'Email',
          displayName: 'Email',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c63',
          apiName: 'EmailBouncedDate',
          displayName: 'Email Bounced Date',
          dataType: 'datetime',
        },
        {
          id: '60e49df87c987b42ccd83c62',
          apiName: 'EmailBouncedReason',
          displayName: 'Email Bounced Reason',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c68',
          apiName: 'HasOptedOutOfEmail',
          displayName: 'Email Opt Out',
          dataType: 'boolean',
        },
        {
          id: '60e49df87c987b42ccd83c45',
          apiName: 'FirstName',
          displayName: 'First Name',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c47',
          apiName: 'Name',
          displayName: 'Full Name',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c64',
          apiName: 'IsEmailBounced',
          displayName: 'Is Email Bounced',
          dataType: 'boolean',
        },
        {
          id: '60e49df87c987b42ccd83c67',
          apiName: 'JigsawContactId',
          displayName: 'Jigsaw Contact ID',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c5b',
          apiName: 'LastModifiedById',
          displayName: 'Last Modified By ID',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83c5a',
          apiName: 'LastModifiedDate',
          displayName: 'Last Modified Date',
          dataType: 'datetime',
        },
        {
          id: '60e49df87c987b42ccd83c44',
          apiName: 'LastName',
          displayName: 'Last Name',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c5e',
          apiName: 'LastCURequestDate',
          displayName: 'Last Stay-in-Touch Request Date',
          dataType: 'datetime',
        },
        {
          id: '60e49df87c987b42ccd83c5f',
          apiName: 'LastCUUpdateDate',
          displayName: 'Last Stay-in-Touch Save Date',
          dataType: 'datetime',
        },
        {
          id: '60e49df87c987b42ccd83c4e',
          apiName: 'MailingCity',
          displayName: 'Mailing City',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c51',
          apiName: 'MailingCountry',
          displayName: 'Mailing Country',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c4f',
          apiName: 'MailingState',
          displayName: 'Mailing State/Province',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c4d',
          apiName: 'MailingStreet',
          displayName: 'Mailing Street',
          dataType: 'textarea',
        },
        {
          id: '60e49df87c987b42ccd83c50',
          apiName: 'MailingPostalCode',
          displayName: 'Mailing Zip/Postal Code',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c42',
          apiName: 'MasterRecordId',
          displayName: 'Master Record ID',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83c53',
          apiName: 'MobilePhone',
          displayName: 'Mobile Phone',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c57',
          apiName: 'OwnerId',
          displayName: 'Owner ID',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83c65',
          apiName: 'PhotoUrl',
          displayName: 'Photo URL',
          dataType: 'url',
        },
        {
          id: '60e49df87c987b42ccd83c46',
          apiName: 'Salutation',
          displayName: 'Salutation',
          dataType: 'picklist',
        },
        {
          id: '60e49df87c987b42ccd83c4a',
          apiName: 'State',
          displayName: 'State/Province',
          dataType: 'string',
        },
        {
          id: '60e49df87c987b42ccd83c48',
          apiName: 'Street',
          displayName: 'Street',
          dataType: 'textarea',
        },
        {
          id: '60e49df87c987b42ccd83c5c',
          apiName: 'SystemModstamp',
          displayName: 'System Modstamp',
          dataType: 'datetime',
        },
        {
          id: '60e49df87c987b42ccd83c55',
          apiName: 'Title',
          displayName: 'Title',
          dataType: 'string',
        },
        {
          id: '60e4cac2532a1b566b936220',
          apiName: 'User_Lookup_One__c',
          displayName: 'User Lookup One',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83c4b',
          apiName: 'PostalCode',
          displayName: 'Zip/Postal Code',
          dataType: 'string',
        },
      ],
    },
    {
      id: '60e49df87c987b42ccd83c11',
      apiName: 'opportunity',
      displayName: 'Opportunity',
      fields: [
        {
          id: '60e49df87c987b42ccd83cd3',
          apiName: 'AccountId',
          displayName: 'Account ID',
          dataType: 'reference',
        },
        {
          id: '60e49df87c987b42ccd83cd7',
          apiName: 'Amount',
          displayName: 'Amount',
          dataType: 'double',
        },
        {
          id: '60e49df87c987b42ccd83cd9',
          apiName: 'CloseDate',
          displayName: 'Close Date',
          dataType: 'date',
        },
      ],
    },
  ],
};
