import { EntityMetricsPayload } from 'store/pipeline-visibility/types';

export const detailsFixture: EntityMetricsPayload = {
  syncariEntityId: '61bd03e66aa831a4d7ec9f68',
  lastProcessed: '2021-12-17T21:42:49.475Z',
  lastSyncTime: '2021-12-17T21:41:49.475Z',
  emptyLastSync: true,
  duration: 40.0,
  durationUnit: 'ms',
  title: 'Last Synced atnull',
  entityName: 'Account',
  apiName: 'account',
  allStages: [
    {
      title: 'Read Sources',
      subtitle: 'Completed 10records',
      totalProcessedRecordsCount: 10,
      recordCountSuffix: 'records',
      lastProcessed: '2021-12-17T21:41:48.472Z',
      durationWithoutConversion: 10.0,
      duration: 10.0,
      durationUnit: 'ms',
      status: 'COMPLETED',
      details: {
        '61bd041b6aa831a4d7eca5b2': {
          connectorId: '61bd041b6aa831a4d7eca5b2',
          connectorName: 'testSynapse',
          connectorEntityName: 'account',
          lastProcessed: '2021-12-17T21:41:48.472Z',
          duration: 10.0,
          totalProcessedRecordsCount: 10,
          skippedCount: 2,
          readCount: 8,
          deletedCount: 0,
          createdCount: 0,
          mergedCount: 0,
          updatedCount: 0,
          durationUnit: 'ms',
        },
      },
    },
    {
      title: 'Executed Sources side EP',
      subtitle: 'Completed 10records',
      totalProcessedRecordsCount: 10,
      recordCountSuffix: 'records',
      lastProcessed: '2021-12-17T21:41:48.473Z',
      durationWithoutConversion: 10.0,
      duration: 10.0,
      durationUnit: 'ms',
      status: 'COMPLETED',
      details: {
        '61bd041b6aa831a4d7eca5b2': {
          connectorId: '61bd041b6aa831a4d7eca5b2',
          connectorName: 'testSynapse',
          connectorEntityName: 'account',
          lastProcessed: '2021-12-17T21:41:48.473Z',
          duration: 10.0,
          totalProcessedRecordsCount: 10,
          skippedCount: 10,
          readCount: 0,
          deletedCount: 0,
          createdCount: 0,
          mergedCount: 0,
          updatedCount: 0,
          durationUnit: 'ms',
        },
      },
    },
    {
      title: 'Executed source side pipeline',
      subtitle: 'Completed 10records',
      totalProcessedRecordsCount: 10,
      recordCountSuffix: 'records',
      lastProcessed: '2021-12-17T21:41:48.474Z',
      durationWithoutConversion: 10.0,
      duration: 10.0,
      durationUnit: 'ms',
      status: 'COMPLETED',
      details: {
        '61bd041b6aa831a4d7eca5b2': {
          connectorId: '61bd041b6aa831a4d7eca5b2',
          connectorName: 'testSynapse',
          connectorEntityName: 'account',
          lastProcessed: '2021-12-17T21:41:48.474Z',
          duration: 10.0,
          totalProcessedRecordsCount: 10,
          skippedCount: 0,
          readCount: 0,
          deletedCount: 2,
          createdCount: 3,
          mergedCount: 0,
          updatedCount: 0,
          durationUnit: 'ms',
        },
      },
    },
    {
      title: 'Executed destination side pipeline',
      subtitle: 'Completed 10records',
      totalProcessedRecordsCount: 10,
      recordCountSuffix: 'records',
      lastProcessed: '2021-12-17T21:41:48.475Z',
      durationWithoutConversion: 10.0,
      duration: 10.0,
      durationUnit: 'ms',
      status: 'COMPLETED',
      details: {
        '61bd041b6aa831a4d7eca5b2': {
          connectorId: '61bd041b6aa831a4d7eca5b2',
          connectorName: 'testSynapse',
          connectorEntityName: 'account',
          lastProcessed: '2021-12-17T21:41:48.475Z',
          duration: 10.0,
          totalProcessedRecordsCount: 10,
          skippedCount: 0,
          readCount: 0,
          deletedCount: 2,
          createdCount: 3,
          mergedCount: 0,
          updatedCount: 0,
          durationUnit: 'ms',
        },
      },
    },
  ],
};

export const detailsFixtureNoStageWithSyncCycle: EntityMetricsPayload = {
  syncariEntityId: '618f06e13c8cbf00011fc6ee',
  lastProcessed: null,
  duration: null,
  durationUnit: 'SECONDS',
  title: 'Synced at2021-12-22T22:40:46.756Z In last sync, there were no new/changed records ',
  entityName: 'Account',
  apiName: 'Account',
  lastSyncTime: '2021-12-22T22:40:46.756Z',
  emptyLastSync: true,
  allStages: null,
};

export const detailsFixtureNoData: EntityMetricsPayload = {
  entityName: '',
  apiName: '',
  syncariEntityId: '60ad30ea2bc6a55388792356',
  emptyLastSync: false,
  lastProcessed: null,
  lastSyncTime: null,
  duration: null,
  durationUnit: 'seconds',
  title: null,
  allStages: null,
};
