//
// Copyright (c) 2019-Present Syncari - All rights reserved.
//
import { getCurrentGraphFixture } from 'store/pipeline/fixtures';
import { fieldPipelineTestRun, pipeline, pipelineTests } from 'store/test/__tests__/selectors.test';
import { TestPanelView, TestRunsModel } from 'store/test/types';
import { mockedAjaxUtils, renderWithRouter, screen } from 'tests/helpers';
import AppConstants from 'utils/AppConstants';
import { tNamespaced } from 'utils/i18nUtil';

import TestResultPanel from '../TestResultPanel';

const tn = tNamespaced('TestResultPanel');
const { FETCH_STATUS } = AppConstants;

// Mocking to prevent unhandled requests printing console errors
jest.mock('utils/AjaxUtil');
const ajaxMock = mockedAjaxUtils();
ajaxMock.get.mockImplementation(jest.fn(() => Promise.resolve()));

interface RenderParams {
  testPanelView?: TestPanelView;
  fieldTestRuns?: TestRunsModel[];
  liveTestRuns?: TestRunsModel[];
}

const renderTestResultPanel = (overrides?: RenderParams) =>
  renderWithRouter(<TestResultPanel pipelineId="1234" pipelineContext={AppConstants.PIPELINE_CONTEXT.FIELD} />, {
    testState: {
      user: { timeZone: 'US/Arizona' },
      entityPipeline: {
        pipelineContext: AppConstants.PIPELINE_CONTEXT.FIELD,
      },
      fieldPipeline: {
        fieldPipeline: pipeline,
      },
      pipeline: {
        // @ts-ignore
        currentGraph: getCurrentGraphFixture(),
      },
      test: {
        testPanelView: overrides?.testPanelView ?? TestPanelView.SIMULATED_RESULTS,
        fieldPipelineTestRun,
        fieldTestRuns: overrides?.fieldTestRuns ?? fieldTestRuns,
        liveTestRuns: overrides?.liveTestRuns ?? fieldTestRuns,
        // @ts-ignore
        liveTestRun: fieldTestRuns[0],
        getFieldTestRunStatus: FETCH_STATUS.SUCCESS,
        getFieldTestRunsStatus: FETCH_STATUS.SUCCESS,
        fieldPipelineTests: pipelineTests,
      },
    },
  });

describe('TestResultPanel', () => {
  test('TestResultPanel render the form without any problem', async () => {
    renderTestResultPanel({ testPanelView: TestPanelView.LIVE_RESULTS });

    expect(await screen.findByText('Live Test Results')).toBeVisible();
    // Check run.runName is converted from UTC time to configured time
    expect(await screen.findByText('4/1/2022 5:00:00 AM MST')).toBeVisible();
  });

  test('TestResultPanel without any test runs', async () => {
    renderTestResultPanel({ fieldTestRuns: [] });

    expect(await screen.findByText('Simulated Test Results')).toBeVisible();
    expect(await screen.findByText(tn('no_simulated_test_runs'))).toBeVisible();
  });
});

const fieldTestRuns = [
  {
    id: '5ffc14dba7c74581c12023ca',
    // Run names are usually the date of the test run, generated by the backend
    // in format 'DD/MM/YYYY hh:mm:ss A'
    runName: '04/01/2022 12:00:00 PM',
    testNames: ['Test1'],
    resultDetails: [],
  },
];
