package com.syncari.core.model.util;

public enum MappingNodeType {

    ATTRIBUTE_SOURCE,ENTITY_SOURCE, FUNCTION, PREDICATE, CORE_ATTRIBUTE,CORE_ENTITY, ACTION, ENTITY_SINK, ATTRIBUTE_SINK,CONNECTOR_ENTITY,GROUP
}
