apiVersion: v1
kind: Service
metadata:
  name: smokescreen-service-$ENVIRONMENT_NAME
spec:
  ports:
  - protocol: TCP
    port: 4750
    targetPort: 4750
  selector:
    app: smokescreen
  type: NodePort