package com.syncari.core.model;

public enum FieldLevelWinnerSelection {
    MOST_RECENTLY_UPDATED_WITH_VALUE, MOST_RECENTLY_CREATED_WITH_VALUE, OLDEST_CREATED_WITH_VALUE, OLDEST_UPDATED_WITH_VALUE, WITH_HIGHEST_VALUE, WITH_LOWEST_VALUE //, WITH_FIRST_MATCHING_VALUE

}