import AppConstants from 'utils/AppConstants';

import { initialState } from './reducer';

export interface GetDataStudioTestStateParams {
  entityId?: string;
}

export const getDataStudioTestState = (params?: GetDataStudioTestStateParams) => {
  const { entityId = 'ASDFASDFASDF' } = params || {};

  return {
    ...initialState,
    entityRecords: {
      [entityId]: {
        '5e67e9f6cfd4bb000115bd52': {
          syncariTimestamp: 1613419057995,
          lastModified: 1584934464000,
          syncariId: '5e67e9f6cfd4bb000115bd52',
          values: {
            LastModifiedDate: '2020-03-08T00:59:35Z',
            IsDeleted: false,
            isDeleted: true,
            IsPublic: true,
            dfi: 7,
            CreatedDate: '2020-03-08T00:59:35Z',
            PhotoUrl: '/services/images/photo/001e000001VJDpvAAH',
            lastModified: 1584934464000,
            syncariTimestamp: 1613419057995,
            syncariId: '5e67e9f6cfd4bb000115bd52',
            Name: 'Unit test 1',
            SystemModstamp: '2020-03-08T00:59:35Z',
          },
          idMapping: {
            SF: '001e000001VJDpvAAH',
          },
          deleted: true,
        },
      },
    },
    entityRecordsListData: {
      [entityId]: {
        records: ['5e67e9f6cfd4bb000115bd52'],
        pageInfo: {
          start: '5e67e9f6cfd4bb000115bd52',
          end: '5e67e9f6cfd4bb000115bd52',
          hasMore: false,
          sorting: [
            {
              columnName: 'Id',
              ascending: true,
            },
          ],
          pageNumber: 0,
          maxPageNumber: 0,
          filteredCount: 20,
          totalCount: 20,
        },
        metadata: {
          selectedColumns: [
            'syncariId',
            'dfi',
            'NumberOfEmployees',
            'Website',
            'BillingCity',
            'BillingLatitude',
            'LastModifiedDate',
            'CloseDate',
            'Name',
            'Industry',
            'CreatedById',
            'OwnerId',
            'BillingLongitude',
            'IsPublic',
            'Phone',
            'AccountSource',
            'BillingGeocodeAccuracy',
            'ShippingCountry',
            'BillingPostalCode',
            'ShippingCity',
            'PhotoUrl',
            'MasterRecordId',
            'ParentId',
            'IsDeleted',
            'AboutUs',
            'ShippingGeocodeAccuracy',
            'TotalMoneyRaised',
            'ShippingStreet',
            'SystemModstamp',
            'Score',
            'Type',
            'BillingCountry',
            'BillingStreet',
            'TwitterHandle',
            'ShippingPostalCode',
            'YearStarted',
            'CreatedDate',
            'ShippingState',
            'SicDesc',
            'LastModifiedById',
            'BillingState',
            'ShippingLongitude',
            'Jigsaw',
            'idMapping',
            'deleted',
          ],
          fields: {
            LastModifiedDate: {
              canDisplay: true,
              dataType: 'datetime',
              canEdit: false,
              label: 'Last Modified Date',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d9',
            },
            BillingCity: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing City',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c7',
            },
            rule_isNotEmpty_BillingCity: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'BillingCity / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_BillingCity',
              fieldId: 'rule_isNotEmpty_BillingCity',
            },
            JigsawCompanyId: {
              canDisplay: true,
              dataType: 'string',
              canEdit: false,
              label: 'Jigsaw Company ID',
              canFilter: true,
              fieldId: '5e7194303f19b0000108cac9',
            },
            rule_isNotEmpty_Phone: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Phone / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_Phone',
              fieldId: 'rule_isNotEmpty_Phone',
            },
            CloseDate: {
              canDisplay: true,
              dataType: 'datetime',
              canEdit: true,
              label: 'Close Date',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e5',
            },
            Name: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Account Name',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c3',
            },
            rule_isNotEmpty_Website: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Website / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_Website',
              fieldId: 'rule_isNotEmpty_Website',
            },
            Industry: {
              canDisplay: true,
              dataType: 'picklist',
              canEdit: true,
              label: 'Industry',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d3',
            },
            rule_isNotEmpty_BillingCountry: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'BillingCountry / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_BillingCountry',
              fieldId: 'rule_isNotEmpty_BillingCountry',
            },
            CreatedById: {
              canDisplay: true,
              dataType: 'reference',
              canEdit: false,
              label: 'Created By ID',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d8',
            },
            IsPublic: {
              canDisplay: true,
              dataType: 'boolean',
              canEdit: true,
              label: 'Is Public',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e1',
            },
            AccountSource: {
              canDisplay: true,
              dataType: 'picklist',
              canEdit: true,
              label: 'Account Source',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85df',
            },
            BillingGeocodeAccuracy: {
              canDisplay: true,
              dataType: 'picklist',
              canEdit: true,
              label: 'Billing Geocode Accuracy',
              canFilter: true,
              fieldId: '5e7156275f3ca0000117768c',
            },
            BillingPostalCode: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing Zip/Postal Code',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c9',
            },
            PhotoUrl: {
              canDisplay: true,
              dataType: 'url',
              canEdit: false,
              label: 'Photo URL',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d2',
            },
            rule_isNotEmpty_BillingPostalCode: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'BillingPostalCode / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_BillingPostalCode',
              fieldId: 'rule_isNotEmpty_BillingPostalCode',
            },
            MasterRecordId: {
              canDisplay: true,
              dataType: 'reference',
              canEdit: false,
              label: 'Master Record ID',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c2',
            },
            IsDeleted: {
              canDisplay: true,
              dataType: 'boolean',
              canEdit: false,
              label: 'Deleted',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c1',
            },
            rule_isPhoneFormatted_Phone: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Phone / IsPhoneFormatted / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isPhoneFormatted_Phone',
              fieldId: 'rule_isPhoneFormatted_Phone',
            },
            dfi: {
              isSystem: true,
              canDisplay: true,
              dataType: 'score',
              canEdit: false,
              label: 'Data Fitness Index',
              canFilter: false,
              fieldId: 'dfi',
            },
            ShippingGeocodeAccuracy: {
              canDisplay: true,
              dataType: 'picklist',
              canEdit: true,
              label: 'Shipping Geocode Accuracy',
              canFilter: true,
              fieldId: '5e7153ed5f3ca00001177665',
            },
            TotalMoneyRaised: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Total Money Raised',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e2',
            },
            ShippingStreet: {
              canDisplay: true,
              dataType: 'textarea',
              canEdit: true,
              label: 'Shipping Street',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85cb',
            },
            Score: {
              canDisplay: true,
              dataType: 'double',
              canEdit: true,
              label: 'Score',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e4',
            },
            TwitterHandle: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Twitter Handle',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e3',
            },
            rule_isNotEmpty_Domain: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Domain / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_Domain',
              fieldId: 'rule_isNotEmpty_Domain',
            },
            ShippingPostalCode: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Shipping Zip/Postal Code',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85ce',
            },
            YearStarted: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Year Started',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85e0',
            },
            rule_isNotEmpty_Name: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Name / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_Name',
              fieldId: 'rule_isNotEmpty_Name',
            },
            CreatedDate: {
              canDisplay: true,
              dataType: 'datetime',
              canEdit: false,
              label: 'Created Date',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d7',
            },
            ShippingState: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Shipping State/Province',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85cd',
            },
            SicDesc: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'SIC Description',
              canFilter: true,
              fieldId: '5e7900db2837370001c25ef5',
            },
            Domain: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Domain',
              canFilter: true,
              fieldId: '5fd065a57df51d113e4a5421',
            },
            AnnualRevenue: {
              canDisplay: true,
              dataType: 'double',
              canEdit: true,
              label: 'Annual Revenue',
              canFilter: true,
              fieldId: '5fd065a57df51d113e4a5422',
            },
            BillingState: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing State/Province',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c8',
            },
            Jigsaw: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Data.com Key',
              canFilter: true,
              fieldId: '5e7190d93f19b0000108caae',
            },
            Description: {
              canDisplay: true,
              dataType: 'textarea',
              canEdit: true,
              label: 'Account Description',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d5',
            },
            Website: {
              canDisplay: true,
              dataType: 'url',
              canEdit: true,
              label: 'Website',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d1',
            },
            BillingLatitude: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing Latitude',
              canFilter: true,
              fieldId: '5e7156965f3ca000011776a5',
            },
            NumberOfEmployees: {
              canDisplay: true,
              dataType: 'integer',
              canEdit: true,
              label: 'Employees',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d4',
            },
            rule_isNotEmpty_NumberOfEmployees: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'NumberOfEmployees / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_NumberOfEmployees',
              fieldId: 'rule_isNotEmpty_NumberOfEmployees',
            },
            syncariId: {
              canDisplay: true,
              dataType: 'string',
              canEdit: false,
              label: 'Syncari Id',
              canFilter: true,
              fieldId: 'datastudio_syncariId',
            },
            datastudio_isDeleted: {
              isSystem: true,
              canDisplay: true,
              dataType: 'boolean',
              canEdit: false,
              label: 'Is Syncari Deleted',
              canFilter: true,
              fieldId: 'datastudio_isDeleted',
            },
            OwnerId: {
              canDisplay: true,
              dataType: 'reference',
              canEdit: true,
              label: 'Owner ID',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d6',
            },
            BillingLongitude: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing Longitude',
              canFilter: true,
              fieldId: '5e7157355f3ca000011776be',
            },
            Phone: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Account Phone',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85d0',
            },
            ShippingCountry: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Shipping Country',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85cf',
            },
            ShippingCity: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Shipping City',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85cc',
            },
            rule_isCamelCased_Name: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'Name / IsCamelCased / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isCamelCased_Name',
              fieldId: 'rule_isCamelCased_Name',
            },
            ParentId: {
              canDisplay: true,
              dataType: 'reference',
              canEdit: true,
              label: 'Parent Account ID',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c5',
            },
            rule_isNotEmpty_AnnualRevenue: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'AnnualRevenue / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_AnnualRevenue',
              fieldId: 'rule_isNotEmpty_AnnualRevenue',
            },
            AboutUs: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'About Us',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c0',
            },
            SystemModstamp: {
              canDisplay: true,
              dataType: 'datetime',
              canEdit: false,
              label: 'System Modstamp',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85db',
            },
            Type: {
              canDisplay: true,
              dataType: 'picklist',
              canEdit: true,
              label: 'Account Type',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c4',
            },
            BillingCountry: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Billing Country',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85ca',
            },
            BillingStreet: {
              canDisplay: true,
              dataType: 'textarea',
              canEdit: true,
              label: 'Billing Street',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85c6',
            },
            rule_isNotEmpty_BillingState: {
              canDisplay: false,
              datatype: 'double',
              canEdit: false,
              label: 'BillingState / IsNotEmpty / Score',
              type: 'variable',
              canFilter: true,
              value: 'rule_isNotEmpty_BillingState',
              fieldId: 'rule_isNotEmpty_BillingState',
            },
            LastModifiedById: {
              canDisplay: true,
              dataType: 'reference',
              canEdit: false,
              label: 'Last Modified By ID',
              canFilter: true,
              fieldId: '5e613d6598a68d0001ab85da',
            },
            ShippingLongitude: {
              canDisplay: true,
              dataType: 'string',
              canEdit: true,
              label: 'Shipping Longitude',
              canFilter: true,
              fieldId: '5e7155365f3ca00001177673',
            },
          },
        },
      },
    },
    entityRecordsListStatus: {
      [entityId]: AppConstants.FETCH_STATUS.SUCCESS,
    },
  };
};
