import { Token } from 'store/tokens/types';

export const tokenSelectorFixture: Record<string, Token[]> = {
  'Lookup Results': [
    {
      value: '60a7d01d33de850001889cbf',
      label: 'syncari / Contact / AE Territory (ae_territory)',
      shortLabel: 'AE Territory',
      token: '{{previousLookup.values.ae_territory}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601166a94769be0001ef5ed4',
      label: 'syncari / Contact / Account Claimed Date (account_claimed_date)',
      shortLabel: 'Account Claimed Date',
      token: '{{previousLookup.values.account_claimed_date}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472fc',
      label: 'syncari / Contact / Account ID (AccountId)',
      shortLabel: 'Account ID',
      token: '{{previousLookup.values.AccountId}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '601166c6893eef00019ea233',
      label: 'syncari / Contact / Activation Date (activation_date)',
      shortLabel: 'Activation Date',
      token: '{{previousLookup.values.activation_date}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6d97758a000153a14f',
      label: 'syncari / Contact / Additional Info - Lead (cf_additional_info_-_lead)',
      shortLabel: 'Additional Info - Lead',
      token: '{{previousLookup.values.cf_additional_info_-_lead}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '60537b2d66c130000186b568',
      label: 'syncari / Contact / Additional email addresses (hs_additional_emails)',
      shortLabel: 'Additional email addresses',
      token: '{{previousLookup.values.hs_additional_emails}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6e97758a000153a164',
      label: 'syncari / Contact / Analyst firm involved?  (cf_analyst_firm_involved)',
      shortLabel: 'Analyst firm involved? ',
      token: '{{previousLookup.values.cf_analyst_firm_involved}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '6177edf14be4810001897a60',
      label:
        'syncari / Contact / Became a Marketing Qualified Lead Date (hs_lifecyclestage_marketingqualifiedlead_date)',
      shortLabel: 'Became a Marketing Qualified Lead Date',
      token: '{{previousLookup.values.hs_lifecyclestage_marketingqualifiedlead_date}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730b',
      label: 'syncari / Contact / Business Phone (Phone)',
      shortLabel: 'Business Phone',
      token: '{{previousLookup.values.Phone}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601164c6893eef00019ea207',
      label: 'syncari / Contact / CSM Owner  (csm_owner)',
      shortLabel: 'CSM Owner ',
      token: '{{previousLookup.values.csm_owner}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6011700b893eef00019ea313',
      label: 'syncari / Contact / Call booked via Chat - LDR (call_via_chat_ldr)',
      shortLabel: 'Call booked via Chat - LDR',
      token: '{{previousLookup.values.call_via_chat_ldr}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601163f04769be0001ef5eae',
      label: 'syncari / Contact / Cancellation Reason (cancellation_reason)',
      shortLabel: 'Cancellation Reason',
      token: '{{previousLookup.values.cancellation_reason}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601166e4893eef00019ea238',
      label: 'syncari / Contact / Chargebee Customer ID (chargebee_customer_id)',
      shortLabel: 'Chargebee Customer ID',
      token: '{{previousLookup.values.chargebee_customer_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6011674a893eef00019ea241',
      label: 'syncari / Contact / Chargebee Site Name (chargebee_site_name)',
      shortLabel: 'Chargebee Site Name',
      token: '{{previousLookup.values.chargebee_site_name}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601167834769be0001ef5ee1',
      label: 'syncari / Contact / Chargebee Site Status (chargebee_site_status)',
      shortLabel: 'Chargebee Site Status',
      token: '{{previousLookup.values.chargebee_site_status}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47302',
      label: 'syncari / Contact / City (City)',
      shortLabel: 'City',
      token: '{{previousLookup.values.City}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6018ffa7dad5c4000143f76d',
      label: 'syncari / Contact / Clearbit - Company Tags (clearbit_company_tags)',
      shortLabel: 'Clearbit - Company Tags',
      token: '{{previousLookup.values.clearbit_company_tags}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6018ffdfdad5c4000143f771',
      label: 'syncari / Contact / Clearbit - Company Tech Categories (clearbit_company_tech)',
      shortLabel: 'Clearbit - Company Tech Categories',
      token: '{{previousLookup.values.clearbit_company_tech}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60190640f1a2180001e9b8d3',
      label: 'syncari / Contact / Clearbit - Employee Size  (clearbit_employee_size)',
      shortLabel: 'Clearbit - Employee Size ',
      token: '{{previousLookup.values.clearbit_employee_size}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60190677f1a2180001e9b8d9',
      label: 'syncari / Contact / Clearbit - Funding Raised  (clearbit_funding_raised)',
      shortLabel: 'Clearbit - Funding Raised ',
      token: '{{previousLookup.values.clearbit_funding_raised}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602526c51e05890001973dc0',
      label: 'syncari / Contact / Clearbit - Industry Group (clearbit_industry_group)',
      shortLabel: 'Clearbit - Industry Group',
      token: '{{previousLookup.values.clearbit_industry_group}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602526deb11dc60001b95542',
      label: 'syncari / Contact / Clearbit - Job Role (clearbit_job_role)',
      shortLabel: 'Clearbit - Job Role',
      token: '{{previousLookup.values.clearbit_job_role}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602526fb1e05890001973dc7',
      label: 'syncari / Contact / Clearbit - Last Enriched On (clearbit_last_enriched)',
      shortLabel: 'Clearbit - Last Enriched On',
      token: '{{previousLookup.values.clearbit_last_enriched}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '6025271eb11dc60001b95545',
      label: 'syncari / Contact / Clearbit - Revenue-Range (clearbit_revenue_classification)',
      shortLabel: 'Clearbit - Revenue-Range',
      token: '{{previousLookup.values.clearbit_revenue_classification}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602527671e05890001973dd4',
      label: 'syncari / Contact / Clearbit - SIC Code (clearbit_sic_code)',
      shortLabel: 'Clearbit - SIC Code',
      token: '{{previousLookup.values.clearbit_sic_code}}',
      datatype: 'integer',
      group: 'Lookup Results',
    },
    {
      value: '602527411e05890001973dcf',
      label: 'syncari / Contact / Clearbit - Sector (clearbit_sector)',
      shortLabel: 'Clearbit - Sector',
      token: '{{previousLookup.values.clearbit_sector}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6025279db11dc60001b9554c',
      label: 'syncari / Contact / Clearbit - Sub Sector (clearbit_sub_sector)',
      shortLabel: 'Clearbit - Sub Sector',
      token: '{{previousLookup.values.clearbit_sub_sector}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602528781e05890001973dea',
      label: 'syncari / Contact / Clearbit Reveal -  Total Employees (clearbit_reveal_total_employees)',
      shortLabel: 'Clearbit Reveal -  Total Employees',
      token: '{{previousLookup.values.clearbit_reveal_total_employees}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602527ceb11dc60001b95551',
      label: 'syncari / Contact / Clearbit Reveal - Company Country (clearbit_reveal_company)',
      shortLabel: 'Clearbit Reveal - Company Country',
      token: '{{previousLookup.values.clearbit_reveal_company}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602527e51e05890001973ddb',
      label: 'syncari / Contact / Clearbit Reveal - Company Employee Range (clearbit_reveal_company_employee_range)',
      shortLabel: 'Clearbit Reveal - Company Employee Range',
      token: '{{previousLookup.values.clearbit_reveal_company_employee_range}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60252807b11dc60001b95557',
      label:
        'syncari / Contact / Clearbit Reveal - Company Estimated Annual Revenue (clearbit_reveal_company_estimated_annual_revenue)',
      shortLabel: 'Clearbit Reveal - Company Estimated Annual Revenue',
      token: '{{previousLookup.values.clearbit_reveal_company_estimated_annual_revenue}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6025282d1e05890001973de3',
      label: 'syncari / Contact / Clearbit Reveal - Company Name (clearbit_reveal_company-name)',
      shortLabel: 'Clearbit Reveal - Company Name',
      token: '{{previousLookup.values.clearbit_reveal_company-name}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60252852b11dc60001b9555b',
      label: 'syncari / Contact / Clearbit Reveal - Company Tags (clearbit_reveal_company_tags)',
      shortLabel: 'Clearbit Reveal - Company Tags',
      token: '{{previousLookup.values.clearbit_reveal_company_tags}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '6099559ac77e6b000146d077',
      label: 'syncari / Contact / ClearbitX Activity (clearbit_x_activity)',
      shortLabel: 'ClearbitX Activity',
      token: '{{previousLookup.values.clearbit_x_activity}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '6171d2849beacf0001311ab5',
      label: 'syncari / Contact / Company Name (company_name)',
      shortLabel: 'Company Name',
      token: '{{previousLookup.values.company_name}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472f9',
      label: 'syncari / Contact / Contact ID (Id)',
      shortLabel: 'Contact ID',
      token: '{{previousLookup.values.Id}}',
      datatype: 'id',
      group: 'Lookup Results',
    },
    {
      value: '60a7d5b833de850001889d8e',
      label: 'syncari / Contact / Continent (continent)',
      shortLabel: 'Continent',
      token: '{{previousLookup.values.continent}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47305',
      label: 'syncari / Contact / Country (Country)',
      shortLabel: 'Country',
      token: '{{previousLookup.values.Country}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6011646c893eef00019ea200',
      label: 'syncari / Contact / Coupons Applied (coupons_applied)',
      shortLabel: 'Coupons Applied',
      token: '{{previousLookup.values.coupons_applied}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47312',
      label: 'syncari / Contact / Created By ID (CreatedById)',
      shortLabel: 'Created By ID',
      token: '{{previousLookup.values.CreatedById}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47311',
      label: 'syncari / Contact / Created Date (CreatedDate)',
      shortLabel: 'Created Date',
      token: '{{previousLookup.values.CreatedDate}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4731f',
      label: 'syncari / Contact / Data.com Key (Jigsaw)',
      shortLabel: 'Data.com Key',
      token: '{{previousLookup.values.Jigsaw}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472fa',
      label: 'syncari / Contact / Deleted (IsDeleted)',
      shortLabel: 'Deleted',
      token: '{{previousLookup.values.IsDeleted}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '60116f17893eef00019ea2fe',
      label: 'syncari / Contact / Demo Booked (Yes/No) (demo_booked_yes_no)',
      shortLabel: 'Demo Booked (Yes/No)',
      token: '{{previousLookup.values.demo_booked_yes_no}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730f',
      label: 'syncari / Contact / Department (Department)',
      shortLabel: 'Department',
      token: '{{previousLookup.values.Department}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116d40893eef00019ea2cf',
      label: 'syncari / Contact / Disco Booked - Territory (disco_booked_territory)',
      shortLabel: 'Disco Booked - Territory',
      token: '{{previousLookup.values.disco_booked_territory}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116d77893eef00019ea2da',
      label: 'syncari / Contact / Disco Booked By (disco_booked_by)',
      shortLabel: 'Disco Booked By',
      token: '{{previousLookup.values.disco_booked_by}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '61310262f0b5d70001c7d436',
      label: 'syncari / Contact / Disco Booked By (Text) (disco_booked_by_text)',
      shortLabel: 'Disco Booked By (Text)',
      token: '{{previousLookup.values.disco_booked_by_text}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116e574769be0001ef5f82',
      label: 'syncari / Contact / Disco Booked On (disco_booked_on)',
      shortLabel: 'Disco Booked On',
      token: '{{previousLookup.values.disco_booked_on}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '60116f6a893eef00019ea308',
      label: 'syncari / Contact / Disco Given On (disco_given_on)',
      shortLabel: 'Disco Given On',
      token: '{{previousLookup.values.disco_given_on}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '604f7019568eab0001cd8f60',
      label: 'syncari / Contact / Disco Status (disco_status)',
      shortLabel: 'Disco Status',
      token: '{{previousLookup.values.disco_status}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116da24769be0001ef5f71',
      label: 'syncari / Contact / Disco scheduled for (disco_scheduled_for)',
      shortLabel: 'Disco scheduled for',
      token: '{{previousLookup.values.disco_scheduled_for}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116dfd893eef00019ea2e3',
      label: 'syncari / Contact / Disco scheduled on (disco_scheduled_on)',
      shortLabel: 'Disco scheduled on',
      token: '{{previousLookup.values.disco_scheduled_on}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '60255e88b11dc60001b95fbc',
      label: 'syncari / Contact / Do not call (do_not_call)',
      shortLabel: 'Do not call',
      token: '{{previousLookup.values.do_not_call}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '60255e99b11dc60001b95fc0',
      label: 'syncari / Contact / Do not email (do_not_email)',
      shortLabel: 'Do not email',
      token: '{{previousLookup.values.do_not_email}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6e97758a000153a15d',
      label: 'syncari / Contact / Drift Summary (cf_drift_summary)',
      shortLabel: 'Drift Summary',
      token: '{{previousLookup.values.cf_drift_summary}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730d',
      label: 'syncari / Contact / Email (Email)',
      shortLabel: 'Email',
      token: '{{previousLookup.values.Email}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4731c',
      label: 'syncari / Contact / Email Bounced Date (EmailBouncedDate)',
      shortLabel: 'Email Bounced Date',
      token: '{{previousLookup.values.EmailBouncedDate}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4731b',
      label: 'syncari / Contact / Email Bounced Reason (EmailBouncedReason)',
      shortLabel: 'Email Bounced Reason',
      token: '{{previousLookup.values.EmailBouncedReason}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116be14769be0001ef5f38',
      label: 'syncari / Contact / Email Deliverability Status (email_deliverability_status)',
      shortLabel: 'Email Deliverability Status',
      token: '{{previousLookup.values.email_deliverability_status}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47321',
      label: 'syncari / Contact / Email Opt Out (HasOptedOutOfEmail)',
      shortLabel: 'Email Opt Out',
      token: '{{previousLookup.values.HasOptedOutOfEmail}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472fe',
      label: 'syncari / Contact / First Name (FirstName)',
      shortLabel: 'First Name',
      token: '{{previousLookup.values.FirstName}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6053c8c83e4301000174c116',
      label: 'syncari / Contact / FreshSales Account ID (freshsales_account_id)',
      shortLabel: 'FreshSales Account ID',
      token: '{{previousLookup.values.freshsales_account_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6053c86e3e4301000174c0f7',
      label: 'syncari / Contact / FreshSales Contact ID (freshsales_contact_id)',
      shortLabel: 'FreshSales Contact ID',
      token: '{{previousLookup.values.freshsales_contact_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '61ae3b088de35300010636b5',
      label: 'syncari / Contact / Freshsales Lead ID (freshsales_lead_id)',
      shortLabel: 'Freshsales Lead ID',
      token: '{{previousLookup.values.freshsales_lead_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47300',
      label: 'syncari / Contact / Full Name (Name)',
      shortLabel: 'Full Name',
      token: '{{previousLookup.values.Name}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60995632c77e6b000146d082',
      label: 'syncari / Contact / G2 Buyer Intent (g2_buyer_intent)',
      shortLabel: 'G2 Buyer Intent',
      token: '{{previousLookup.values.g2_buyer_intent}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '6011650f4769be0001ef5eba',
      label: 'syncari / Contact / Gateways Configured (gateways_configured)',
      shortLabel: 'Gateways Configured',
      token: '{{previousLookup.values.gateways_configured}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116aec4769be0001ef5f18',
      label: 'syncari / Contact / HS - Weighted Score  (hubspot_weighted_score)',
      shortLabel: 'HS - Weighted Score ',
      token: '{{previousLookup.values.hubspot_weighted_score}}',
      datatype: 'integer',
      group: 'Lookup Results',
    },
    {
      value: '6130ff01b772140001d2b714',
      label: 'syncari / Contact / Has Deal (HasDeal)',
      shortLabel: 'Has Deal',
      token: '{{previousLookup.values.HasDeal}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '601165bb4769be0001ef5ec8',
      label: 'syncari / Contact / Hosted Region (hosted_region)',
      shortLabel: 'Hosted Region',
      token: '{{previousLookup.values.hosted_region}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6196274fe0d17c0001b44634',
      label: 'syncari / Contact / How did you hear about us? (how_did_you_hear_about_us_)',
      shortLabel: 'How did you hear about us?',
      token: '{{previousLookup.values.how_did_you_hear_about_us_}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6053c88c3e4301000174c0fb',
      label: 'syncari / Contact / Hubspot Company ID (hubspot_company_id)',
      shortLabel: 'Hubspot Company ID',
      token: '{{previousLookup.values.hubspot_company_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '612e74b21cda310001bc426b',
      label: 'syncari / Contact / Hubspot Contact Created Date (hubspot_created_date)',
      shortLabel: 'Hubspot Contact Created Date',
      token: '{{previousLookup.values.hubspot_created_date}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '6011a3ab893eef00019eaace',
      label: 'syncari / Contact / Hubspot Contact ID (hubspot_contact_id)',
      shortLabel: 'Hubspot Contact ID',
      token: '{{previousLookup.values.hubspot_contact_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601165f34769be0001ef5ece',
      label: 'syncari / Contact / Integrations Enabled (integrations_enabled)',
      shortLabel: 'Integrations Enabled',
      token: '{{previousLookup.values.integrations_enabled}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4731d',
      label: 'syncari / Contact / Is Email Bounced (IsEmailBounced)',
      shortLabel: 'Is Email Bounced',
      token: '{{previousLookup.values.IsEmailBounced}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '60116c7c4769be0001ef5f53',
      label: 'syncari / Contact / Is Role Based Email (is_role_based_email)',
      shortLabel: 'Is Role Based Email',
      token: '{{previousLookup.values.is_role_based_email}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116c27893eef00019ea292',
      label: 'syncari / Contact / Is disposable email (is_disposable_email)',
      shortLabel: 'Is disposable email',
      token: '{{previousLookup.values.is_disposable_email}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116c51893eef00019ea29d',
      label: 'syncari / Contact / Is free Email (is_free_email)',
      shortLabel: 'Is free Email',
      token: '{{previousLookup.values.is_free_email}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47320',
      label: 'syncari / Contact / Jigsaw Contact ID (JigsawContactId)',
      shortLabel: 'Jigsaw Contact ID',
      token: '{{previousLookup.values.JigsawContactId}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '61962750e0d17c0001b4463b',
      label: 'syncari / Contact / Key Challenge to Trigger CB evaluation (key_challenge_to_trigger_cb_evaluation)',
      shortLabel: 'Key Challenge to Trigger CB evaluation',
      token: '{{previousLookup.values.key_challenge_to_trigger_cb_evaluation}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601170324769be0001ef5fa5',
      label: 'syncari / Contact / LDR Notes (ldr_notes)',
      shortLabel: 'LDR Notes',
      token: '{{previousLookup.values.ldr_notes}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47314',
      label: 'syncari / Contact / Last Modified By ID (LastModifiedById)',
      shortLabel: 'Last Modified By ID',
      token: '{{previousLookup.values.LastModifiedById}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47313',
      label: 'syncari / Contact / Last Modified Date (LastModifiedDate)',
      shortLabel: 'Last Modified Date',
      token: '{{previousLookup.values.LastModifiedDate}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472fd',
      label: 'syncari / Contact / Last Name (LastName)',
      shortLabel: 'Last Name',
      token: '{{previousLookup.values.LastName}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47317',
      label: 'syncari / Contact / Last Stay-in-Touch Request Date (LastCURequestDate)',
      shortLabel: 'Last Stay-in-Touch Request Date',
      token: '{{previousLookup.values.LastCURequestDate}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47318',
      label: 'syncari / Contact / Last Stay-in-Touch Save Date (LastCUUpdateDate)',
      shortLabel: 'Last Stay-in-Touch Save Date',
      token: '{{previousLookup.values.LastCUUpdateDate}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '6177edf14be4810001897a6f',
      label: 'syncari / Contact / Lead ID (cf_lead_id)',
      shortLabel: 'Lead ID',
      token: '{{previousLookup.values.cf_lead_id}}',
      datatype: 'double',
      group: 'Lookup Results',
    },
    {
      value: '611542fb96179500013df005',
      label: 'syncari / Contact / Lead Source (FS) (lead_source_fs)',
      shortLabel: 'Lead Source (FS)',
      token: '{{previousLookup.values.lead_source_fs}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60a7e20b33de85000188a10e',
      label: 'syncari / Contact / Lead Stage (FS) (lead_stage_fs)',
      shortLabel: 'Lead Stage (FS)',
      token: '{{previousLookup.values.lead_stage_fs}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60f9b9368674ff0001014342',
      label: 'syncari / Contact / Lifecycle Stage (lifecyclestage)',
      shortLabel: 'Lifecycle Stage',
      token: '{{previousLookup.values.lifecyclestage}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47307',
      label: 'syncari / Contact / Mailing City (MailingCity)',
      shortLabel: 'Mailing City',
      token: '{{previousLookup.values.MailingCity}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730a',
      label: 'syncari / Contact / Mailing Country (MailingCountry)',
      shortLabel: 'Mailing Country',
      token: '{{previousLookup.values.MailingCountry}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47308',
      label: 'syncari / Contact / Mailing State/Province (MailingState)',
      shortLabel: 'Mailing State/Province',
      token: '{{previousLookup.values.MailingState}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47306',
      label: 'syncari / Contact / Mailing Street (MailingStreet)',
      shortLabel: 'Mailing Street',
      token: '{{previousLookup.values.MailingStreet}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47309',
      label: 'syncari / Contact / Mailing Zip/Postal Code (MailingPostalCode)',
      shortLabel: 'Mailing Zip/Postal Code',
      token: '{{previousLookup.values.MailingPostalCode}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116cc1893eef00019ea2af',
      label: 'syncari / Contact / Marketing Conversions Mode (marketing_conversions_mode)',
      shortLabel: 'Marketing Conversions Mode',
      token: '{{previousLookup.values.marketing_conversions_mode}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60116cf3893eef00019ea2b6',
      label: 'syncari / Contact / Marketing Medium (marketing_medium)',
      shortLabel: 'Marketing Medium',
      token: '{{previousLookup.values.marketing_medium}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472fb',
      label: 'syncari / Contact / Master Record ID (MasterRecordId)',
      shortLabel: 'Master Record ID',
      token: '{{previousLookup.values.MasterRecordId}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '6177edf14be4810001897a65',
      label: 'syncari / Contact / Medium (medium)',
      shortLabel: 'Medium',
      token: '{{previousLookup.values.medium}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6140bcb84c9ccc0001fea3b5',
      label: 'syncari / Contact / Merged object IDs (hs_merged_object_ids)',
      shortLabel: 'Merged object IDs',
      token: '{{previousLookup.values.hs_merged_object_ids}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730c',
      label: 'syncari / Contact / Mobile Phone (MobilePhone)',
      shortLabel: 'Mobile Phone',
      token: '{{previousLookup.values.MobilePhone}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '609956b5c77e6b000146d08c',
      label: 'syncari / Contact / Most Recent Campaign (recent_campaign_hs)',
      shortLabel: 'Most Recent Campaign',
      token: '{{previousLookup.values.recent_campaign_hs}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '6177edf14be4810001897a74',
      label: 'syncari / Contact / Original Source Drill-Down 1 (hs_analytics_source_data_1)',
      shortLabel: 'Original Source Drill-Down 1',
      token: '{{previousLookup.values.hs_analytics_source_data_1}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6177edf14be4810001897a6a',
      label: 'syncari / Contact / Original Source Drill-Down 2 (hs_analytics_source_data_2)',
      shortLabel: 'Original Source Drill-Down 2',
      token: '{{previousLookup.values.hs_analytics_source_data_2}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6d97758a000153a156',
      label: 'syncari / Contact / Outbound lead present in SL (cf_outbound_lead_present_in_sl)',
      shortLabel: 'Outbound lead present in SL',
      token: '{{previousLookup.values.cf_outbound_lead_present_in_sl}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47310',
      label: 'syncari / Contact / Owner ID (OwnerId)',
      shortLabel: 'Owner ID',
      token: '{{previousLookup.values.OwnerId}}',
      datatype: 'reference',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6d97758a000153a148',
      label: 'syncari / Contact / Partner name (cf_partner_name)',
      shortLabel: 'Partner name',
      token: '{{previousLookup.values.cf_partner_name}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6099567dc77e6b000146d089',
      label: 'syncari / Contact / Persona SL (persona_sl)',
      shortLabel: 'Persona SL',
      token: '{{previousLookup.values.persona_sl}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4731e',
      label: 'syncari / Contact / Photo URL (PhotoUrl)',
      shortLabel: 'Photo URL',
      token: '{{previousLookup.values.PhotoUrl}}',
      datatype: 'url',
      group: 'Lookup Results',
    },
    {
      value: '60116624893eef00019ea218',
      label: 'syncari / Contact / Plan (plan)',
      shortLabel: 'Plan',
      token: '{{previousLookup.values.plan}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601167ba893eef00019ea24c',
      label: 'syncari / Contact / Plan Type On Activation (plan_type_on_activation)',
      shortLabel: 'Plan Type On Activation',
      token: '{{previousLookup.values.plan_type_on_activation}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6155ac6e97758a000153a16b',
      label: 'syncari / Contact / Product limitation - Feature requested (cf_product_limitation_-_feature_requested)',
      shortLabel: 'Product limitation - Feature requested',
      token: '{{previousLookup.values.cf_product_limitation_-_feature_requested}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60f9b4978674ff0001013ff2',
      label: 'syncari / Contact / Recent note (recent_note)',
      shortLabel: 'Recent note',
      token: '{{previousLookup.values.recent_note}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '60a7cf7133de850001889bae',
      label: 'syncari / Contact / Revenue Segment (SDR) (revenue_segment_sdr)',
      shortLabel: 'Revenue Segment (SDR)',
      token: '{{previousLookup.values.revenue_segment_sdr}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6099556033bcff0001dff951',
      label: 'syncari / Contact / Rollworks Last Activity (rollworks_last_activity)',
      shortLabel: 'Rollworks Last Activity',
      token: '{{previousLookup.values.rollworks_last_activity}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '60a7d78f56203e00011d34da',
      label: 'syncari / Contact / SDR Call Scheduled On (sdr_call_scheduled_on)',
      shortLabel: 'SDR Call Scheduled On',
      token: '{{previousLookup.values.sdr_call_scheduled_on}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '60a7d77856203e00011d34d5',
      label: 'syncari / Contact / SDR Call booked on (sdr_call_booked_on)',
      shortLabel: 'SDR Call booked on',
      token: '{{previousLookup.values.sdr_call_booked_on}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '6053c8aa68b6460001dcb432',
      label: 'syncari / Contact / SalesLoft Account ID (salesloft_account_id)',
      shortLabel: 'SalesLoft Account ID',
      token: '{{previousLookup.values.salesloft_account_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601170a94769be0001ef5fae',
      label: 'syncari / Contact / Salesloft - Person Stage (salesloft_person_stage)',
      shortLabel: 'Salesloft - Person Stage',
      token: '{{previousLookup.values.salesloft_person_stage}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6011708c4769be0001ef5fa9',
      label: 'syncari / Contact / Salesloft Contact ID (salesloft_contact_id)',
      shortLabel: 'Salesloft Contact ID',
      token: '{{previousLookup.values.salesloft_contact_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6099566533bcff0001dff968',
      label: 'syncari / Contact / Salesloft Last Contacted At (sl_last_contacted_at)',
      shortLabel: 'Salesloft Last Contacted At',
      token: '{{previousLookup.values.sl_last_contacted_at}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '60d5f9eac99fc2000129bf2f',
      label: 'syncari / Contact / Salesloft Last Contacted Type (last_contacted_type)',
      shortLabel: 'Salesloft Last Contacted Type',
      token: '{{previousLookup.values.last_contacted_type}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b472ff',
      label: 'syncari / Contact / Salutation (Salutation)',
      shortLabel: 'Salutation',
      token: '{{previousLookup.values.Salutation}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '60255e1db11dc60001b95fb7',
      label: 'syncari / Contact / Source (source)',
      shortLabel: 'Source',
      token: '{{previousLookup.values.source}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47303',
      label: 'syncari / Contact / State/Province (State)',
      shortLabel: 'State/Province',
      token: '{{previousLookup.values.State}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60f9b72d5e596f00016da6ae',
      label: 'syncari / Contact / Status (contact_status_id)',
      shortLabel: 'Status',
      token: '{{previousLookup.values.contact_status_id}}',
      datatype: 'picklist',
      group: 'Lookup Results',
    },
    {
      value: '611132f23304f200014156c4',
      label: 'syncari / Contact / Status Text (StatusText)',
      shortLabel: 'Status Text',
      token: '{{previousLookup.values.StatusText}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47301',
      label: 'syncari / Contact / Street (Street)',
      shortLabel: 'Street',
      token: '{{previousLookup.values.Street}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '60116672893eef00019ea220',
      label: 'syncari / Contact / Subscription Status (subscription_status)',
      shortLabel: 'Subscription Status',
      token: '{{previousLookup.values.subscription_status}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47315',
      label: 'syncari / Contact / System Modstamp (SystemModstamp)',
      shortLabel: 'System Modstamp',
      token: '{{previousLookup.values.SystemModstamp}}',
      datatype: 'datetime',
      group: 'Lookup Results',
    },
    {
      value: '6129339bf7ddab000135021c',
      label: 'syncari / Contact / Target Account Tier (target_account_tier)',
      shortLabel: 'Target Account Tier',
      token: '{{previousLookup.values.target_account_tier}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b4730e',
      label: 'syncari / Contact / Title (Title)',
      shortLabel: 'Title',
      token: '{{previousLookup.values.Title}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '601169d54769be0001ef5efc',
      label: 'syncari / Contact / Trial end date (trial_end_date)',
      shortLabel: 'Trial end date',
      token: '{{previousLookup.values.trial_end_date}}',
      datatype: 'date',
      group: 'Lookup Results',
    },
    {
      value: '6171d5869beacf0001311c0f',
      label: 'syncari / Contact / Website (website)',
      shortLabel: 'Website',
      token: '{{previousLookup.values.website}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602528a7b11dc60001b95560',
      label: 'syncari / Contact / ZI - All Industries (zi_all_industries)',
      shortLabel: 'ZI - All Industries',
      token: '{{previousLookup.values.zi_all_industries}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602528d5b11dc60001b95564',
      label: 'syncari / Contact / ZI - All Sub Industries (zi_all_sub_industries)',
      shortLabel: 'ZI - All Sub Industries',
      token: '{{previousLookup.values.zi_all_sub_industries}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '602528eab11dc60001b9556b',
      label: 'syncari / Contact / ZI - Company Revenue (zi_company_revenue)',
      shortLabel: 'ZI - Company Revenue',
      token: '{{previousLookup.values.zi_company_revenue}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602529001e05890001973df1',
      label: 'syncari / Contact / ZI - Company Revenue Range (zi_company_revenue_range)',
      shortLabel: 'ZI - Company Revenue Range',
      token: '{{previousLookup.values.zi_company_revenue_range}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602529261e05890001973df6',
      label: 'syncari / Contact / ZI - Industry (zi_industry)',
      shortLabel: 'ZI - Industry',
      token: '{{previousLookup.values.zi_industry}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6025293cb11dc60001b95570',
      label: 'syncari / Contact / ZI - LinkedIn Url (zi_linkedin_url)',
      shortLabel: 'ZI - LinkedIn Url',
      token: '{{previousLookup.values.zi_linkedin_url}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60252952b11dc60001b95574',
      label: 'syncari / Contact / ZI - Primary Industry (zi_primary_industry)',
      shortLabel: 'ZI - Primary Industry',
      token: '{{previousLookup.values.zi_primary_industry}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602529761e05890001973dfc',
      label: 'syncari / Contact / ZI - Primary Sub Industry (zi_primary_sub_industry)',
      shortLabel: 'ZI - Primary Sub Industry',
      token: '{{previousLookup.values.zi_primary_sub_industry}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '6025298d1e05890001973e01',
      label: 'syncari / Contact / ZI - Technologies (zi_technologies)',
      shortLabel: 'ZI - Technologies',
      token: '{{previousLookup.values.zi_technologies}}',
      datatype: 'textarea',
      group: 'Lookup Results',
    },
    {
      value: '5ff36474391cf50001b47304',
      label: 'syncari / Contact / Zip/Postal Code (PostalCode)',
      shortLabel: 'Zip/Postal Code',
      token: '{{previousLookup.values.PostalCode}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '602529f9b11dc60001b9557b',
      label: 'syncari / Contact / ZoomInfo Company ID (zoominfo_company_id)',
      shortLabel: 'ZoomInfo Company ID',
      token: '{{previousLookup.values.zoominfo_company_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '60252a15b11dc60001b9557f',
      label: 'syncari / Contact / ZoomInfo Contact ID (zoominfo_contact_id)',
      shortLabel: 'ZoomInfo Contact ID',
      token: '{{previousLookup.values.zoominfo_contact_id}}',
      datatype: 'string',
      group: 'Lookup Results',
    },
    {
      value: '617bfa5d7013340001324e9f',
      label: 'syncari / Contact / forcedestination (forcedestination)',
      shortLabel: 'forcedestination',
      token: '{{previousLookup.values.forcedestination}}',
      datatype: 'boolean',
      group: 'Lookup Results',
    },
  ],
  Syncari: [
    {
      value: '6049fcb74cdff300011622ab',
      label: 'syncari / Lead / AE territory (ae_territory)',
      shortLabel: 'AE territory',
      token: '{{record.values.ae_territory}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a04741230f30001f6d828',
      label: 'syncari / Lead / Assignee email (SDR) (assignee_email_sdr)',
      shortLabel: 'Assignee email (SDR)',
      token: '{{record.values.assignee_email_sdr}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a04a91230f30001f6d833',
      label: 'syncari / Lead / Calendar Booking Source (calendar_booking_source)',
      shortLabel: 'Calendar Booking Source',
      token: '{{record.values.calendar_booking_source}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a04851230f30001f6d82c',
      label: 'syncari / Lead / Call Scheduled date (call_scheduled_date)',
      shortLabel: 'Call Scheduled date',
      token: '{{record.values.call_scheduled_date}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '604a00934cdff300011622f2',
      label: 'syncari / Lead / Call booked via Chat - LDR (call_booked_via_chat_ldr)',
      shortLabel: 'Call booked via Chat - LDR',
      token: '{{record.values.call_booked_via_chat_ldr}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732d',
      label: 'syncari / Lead / City (City)',
      shortLabel: 'City',
      token: '{{record.values.City}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a13ac4cdff300011624f4',
      label: 'syncari / Lead / Clearbit - Company Tags (clearbit_company_tags)',
      shortLabel: 'Clearbit - Company Tags',
      token: '{{record.values.clearbit_company_tags}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a13bf4cdff300011624fb',
      label: 'syncari / Lead / Clearbit - Company Tech Categories (clearbit_company_tech)',
      shortLabel: 'Clearbit - Company Tech Categories',
      token: '{{record.values.clearbit_company_tech}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a13d91230f30001f6da5b',
      label: 'syncari / Lead / Clearbit - Employee Size (clearbit_employee_size)',
      shortLabel: 'Clearbit - Employee Size',
      token: '{{record.values.clearbit_employee_size}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a13f11230f30001f6da5f',
      label: 'syncari / Lead / Clearbit - Funding Raised  (clearbit_funding_raised)',
      shortLabel: 'Clearbit - Funding Raised ',
      token: '{{record.values.clearbit_funding_raised}}',
      datatype: 'integer',
      group: 'Syncari',
    },
    {
      value: '604a14014cdff30001162509',
      label: 'syncari / Lead / Clearbit - Industry Group (clearbit_industry_group)',
      shortLabel: 'Clearbit - Industry Group',
      token: '{{record.values.clearbit_industry_group}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a14131230f30001f6da68',
      label: 'syncari / Lead / Clearbit - Job Role (clearbit_job_role)',
      shortLabel: 'Clearbit - Job Role',
      token: '{{record.values.clearbit_job_role}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a14274cdff30001162516',
      label: 'syncari / Lead / Clearbit - Last Enriched On (clearbit_last_enriched)',
      shortLabel: 'Clearbit - Last Enriched On',
      token: '{{record.values.clearbit_last_enriched}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '604a143e1230f30001f6da7f',
      label: 'syncari / Lead / Clearbit - Revenue Classification (clearbit_revenue_classification)',
      shortLabel: 'Clearbit - Revenue Classification',
      token: '{{record.values.clearbit_revenue_classification}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a14574cdff3000116252f',
      label: 'syncari / Lead / Clearbit - Revenue-Range (clearbit_revenue_range)',
      shortLabel: 'Clearbit - Revenue-Range',
      token: '{{record.values.clearbit_revenue_range}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a147f4cdff30001162536',
      label: 'syncari / Lead / Clearbit - SIC Code (clearbit_sic_code)',
      shortLabel: 'Clearbit - SIC Code',
      token: '{{record.values.clearbit_sic_code}}',
      datatype: 'integer',
      group: 'Syncari',
    },
    {
      value: '604a146e1230f30001f6da89',
      label: 'syncari / Lead / Clearbit - Sector (clearbit_sector)',
      shortLabel: 'Clearbit - Sector',
      token: '{{record.values.clearbit_sector}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a14914cdff3000116253c',
      label: 'syncari / Lead / Clearbit - Sub Sector (clearbit_sub_sector)',
      shortLabel: 'Clearbit - Sub Sector',
      token: '{{record.values.clearbit_sub_sector}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732b',
      label: 'syncari / Lead / Company (Company)',
      shortLabel: 'Company',
      token: '{{record.values.Company}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733e',
      label: 'syncari / Lead / Converted (IsConverted)',
      shortLabel: 'Converted',
      token: '{{record.values.IsConverted}}',
      datatype: 'boolean',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47340',
      label: 'syncari / Lead / Converted Account ID (ConvertedAccountId)',
      shortLabel: 'Converted Account ID',
      token: '{{record.values.ConvertedAccountId}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47341',
      label: 'syncari / Lead / Converted Contact ID (ConvertedContactId)',
      shortLabel: 'Converted Contact ID',
      token: '{{record.values.ConvertedContactId}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733f',
      label: 'syncari / Lead / Converted Date (ConvertedDate)',
      shortLabel: 'Converted Date',
      token: '{{record.values.ConvertedDate}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47342',
      label: 'syncari / Lead / Converted Opportunity ID (ConvertedOpportunityId)',
      shortLabel: 'Converted Opportunity ID',
      token: '{{record.values.ConvertedOpportunityId}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47330',
      label: 'syncari / Lead / Country (Country)',
      shortLabel: 'Country',
      token: '{{record.values.Country}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47345',
      label: 'syncari / Lead / Created By ID (CreatedById)',
      shortLabel: 'Created By ID',
      token: '{{record.values.CreatedById}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47344',
      label: 'syncari / Lead / Created Date (CreatedDate)',
      shortLabel: 'Created Date',
      token: '{{record.values.CreatedDate}}',
      datatype: 'datetime',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4734c',
      label: 'syncari / Lead / Data.com Key (Jigsaw)',
      shortLabel: 'Data.com Key',
      token: '{{record.values.Jigsaw}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47324',
      label: 'syncari / Lead / Deleted (IsDeleted)',
      shortLabel: 'Deleted',
      token: '{{record.values.IsDeleted}}',
      datatype: 'boolean',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47339',
      label: 'syncari / Lead / Description (Description)',
      shortLabel: 'Description',
      token: '{{record.values.Description}}',
      datatype: 'textarea',
      group: 'Syncari',
    },
    {
      value: '604a002e4cdff300011622e9',
      label: 'syncari / Lead / Disco Booked (Y/N) (disco_booked_yn)',
      shortLabel: 'Disco Booked (Y/N)',
      token: '{{record.values.disco_booked_yn}}',
      datatype: 'boolean',
      group: 'Syncari',
    },
    {
      value: '6049fcca1230f30001f6d7ac',
      label: 'syncari / Lead / Disco Booked By (ref ID) (disco_booked_by)',
      shortLabel: 'Disco Booked By (ref ID)',
      token: '{{record.values.disco_booked_by}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '61281abf0f9bbe0001048788',
      label: 'syncari / Lead / Disco Booked By (text) (disco_booked_by_text)',
      shortLabel: 'Disco Booked By (text)',
      token: '{{record.values.disco_booked_by_text}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '6049fdca1230f30001f6d7b8',
      label: 'syncari / Lead / Disco Scheduled on (disco_scheduled_on)',
      shortLabel: 'Disco Scheduled on',
      token: '{{record.values.disco_scheduled_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '6049ffb21230f30001f6d7e2',
      label: 'syncari / Lead / Disco Status (disco_status)',
      shortLabel: 'Disco Status',
      token: '{{record.values.disco_status}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '6049fe111230f30001f6d7be',
      label: 'syncari / Lead / Disco booked on (disco_booked_on)',
      shortLabel: 'Disco booked on',
      token: '{{record.values.disco_booked_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '604a00461230f30001f6d7ed',
      label: 'syncari / Lead / Disco given on (disco_given_on)',
      shortLabel: 'Disco given on',
      token: '{{record.values.disco_given_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '6049fd1c4cdff300011622b1',
      label: 'syncari / Lead / Disco scheduled for (disco_scheduled_for)',
      shortLabel: 'Disco scheduled for',
      token: '{{record.values.disco_scheduled_for}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47336',
      label: 'syncari / Lead / Email (Email)',
      shortLabel: 'Email',
      token: '{{record.values.Email}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4734f',
      label: 'syncari / Lead / Email Bounced Date (EmailBouncedDate)',
      shortLabel: 'Email Bounced Date',
      token: '{{record.values.EmailBouncedDate}}',
      datatype: 'datetime',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4734e',
      label: 'syncari / Lead / Email Bounced Reason (EmailBouncedReason)',
      shortLabel: 'Email Bounced Reason',
      token: '{{record.values.EmailBouncedReason}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a01801230f30001f6d7ff',
      label: 'syncari / Lead / Email Deliverability Status (email_deliverability_status)',
      shortLabel: 'Email Deliverability Status',
      token: '{{record.values.email_deliverability_status}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733c',
      label: 'syncari / Lead / Employees (NumberOfEmployees)',
      shortLabel: 'Employees',
      token: '{{record.values.NumberOfEmployees}}',
      datatype: 'integer',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47327',
      label: 'syncari / Lead / First Name (FirstName)',
      shortLabel: 'First Name',
      token: '{{record.values.FirstName}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '60411b90928d1e0001d28ec3',
      label: 'syncari / Lead / Freshsales Lead ID (fs_lead_id)',
      shortLabel: 'Freshsales Lead ID',
      token: '{{record.values.fs_lead_id}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47329',
      label: 'syncari / Lead / Full Name (Name)',
      shortLabel: 'Full Name',
      token: '{{record.values.Name}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47333',
      label: 'syncari / Lead / Geocode Accuracy (GeocodeAccuracy)',
      shortLabel: 'Geocode Accuracy',
      token: '{{record.values.GeocodeAccuracy}}',
      datatype: 'picklist',
      group: 'Syncari',
    },
    {
      value: '61962defdd4a440001422cef',
      label: 'syncari / Lead / How did you hear about us? (how_did_you_hear_about_us)',
      shortLabel: 'How did you hear about us?',
      token: '{{record.values.how_did_you_hear_about_us}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604117261abafd0001377453',
      label: 'syncari / Lead / Hubspot Contact ID (hubspot_contact_id)',
      shortLabel: 'Hubspot Contact ID',
      token: '{{record.values.hubspot_contact_id}}',
      datatype: 'integer',
      group: 'Syncari',
    },
    {
      value: '6128b412f7ddab000134ddba',
      label: 'syncari / Lead / Hubspot Contact ID (Text) (hubspot_contact_id_text)',
      shortLabel: 'Hubspot Contact ID (Text)',
      token: '{{record.values.hubspot_contact_id_text}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733b',
      label: 'syncari / Lead / Industry (Industry)',
      shortLabel: 'Industry',
      token: '{{record.values.Industry}}',
      datatype: 'picklist',
      group: 'Syncari',
    },
    {
      value: '604a02021230f30001f6d80d',
      label: 'syncari / Lead / Is Free Email (is_free_email)',
      shortLabel: 'Is Free Email',
      token: '{{record.values.is_free_email}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a03064cdff30001162311',
      label: 'syncari / Lead / Is Role Based Email (is_role_based_email)',
      shortLabel: 'Is Role Based Email',
      token: '{{record.values.is_role_based_email}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a01b51230f30001f6d80a',
      label: 'syncari / Lead / Is disposable email (is_disposable_email)',
      shortLabel: 'Is disposable email',
      token: '{{record.values.is_disposable_email}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4734d',
      label: 'syncari / Lead / Jigsaw Contact ID (JigsawContactId)',
      shortLabel: 'Jigsaw Contact ID',
      token: '{{record.values.JigsawContactId}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '61962e0ddd4a440001422cf2',
      label: 'syncari / Lead / Key challenge to trigger CB evaluation (key_challenge_to_trigger_CB_evaluation)',
      shortLabel: 'Key challenge to trigger CB evaluation',
      token: '{{record.values.key_challenge_to_trigger_CB_evaluation}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a48be4cdff30001163c69',
      label: 'syncari / Lead / LDR Call booked date (ldr_call_booked_date)',
      shortLabel: 'LDR Call booked date',
      token: '{{record.values.ldr_call_booked_date}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47347',
      label: 'syncari / Lead / Last Modified By ID (LastModifiedById)',
      shortLabel: 'Last Modified By ID',
      token: '{{record.values.LastModifiedById}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47346',
      label: 'syncari / Lead / Last Modified Date (LastModifiedDate)',
      shortLabel: 'Last Modified Date',
      token: '{{record.values.LastModifiedDate}}',
      datatype: 'datetime',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47326',
      label: 'syncari / Lead / Last Name (LastName)',
      shortLabel: 'Last Name',
      token: '{{record.values.LastName}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47331',
      label: 'syncari / Lead / Latitude (Latitude)',
      shortLabel: 'Latitude',
      token: '{{record.values.Latitude}}',
      datatype: 'double',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47323',
      label: 'syncari / Lead / Lead ID (Id)',
      shortLabel: 'Lead ID',
      token: '{{record.values.Id}}',
      datatype: 'id',
      group: 'Syncari',
    },
    {
      value: '6115423b1af49d0001b9316f',
      label: 'syncari / Lead / Lead Source (lead_source)',
      shortLabel: 'Lead Source',
      token: '{{record.values.lead_source}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604f74da568eab0001cd9013',
      label: 'syncari / Lead / Lead Stage (lead_stage)',
      shortLabel: 'Lead Stage',
      token: '{{record.values.lead_stage}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47332',
      label: 'syncari / Lead / Longitude (Longitude)',
      shortLabel: 'Longitude',
      token: '{{record.values.Longitude}}',
      datatype: 'double',
      group: 'Syncari',
    },
    {
      value: '604a010a4cdff300011622f8',
      label: 'syncari / Lead / Marketing Conversions Mode (marketing_conversions_mode)',
      shortLabel: 'Marketing Conversions Mode',
      token: '{{record.values.marketing_conversions_mode}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a011b4cdff300011622fa',
      label: 'syncari / Lead / Marketing Medium (marketing_medium)',
      shortLabel: 'Marketing Medium',
      token: '{{record.values.marketing_medium}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47325',
      label: 'syncari / Lead / Master Record ID (MasterRecordId)',
      shortLabel: 'Master Record ID',
      token: '{{record.values.MasterRecordId}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '6177ee778ccf2100015d3049',
      label: 'syncari / Lead / Medium (medium)',
      shortLabel: 'Medium',
      token: '{{record.values.medium}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a04954cdff30001162322',
      label: 'syncari / Lead / Meeting Booked on (meeting_booked_on)',
      shortLabel: 'Meeting Booked on',
      token: '{{record.values.meeting_booked_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47335',
      label: 'syncari / Lead / Mobile Phone (MobilePhone)',
      shortLabel: 'Mobile Phone',
      token: '{{record.values.MobilePhone}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a00671230f30001f6d7f1',
      label: 'syncari / Lead / Nurturing Qualified Reason (nurturing_qualified_reason)',
      shortLabel: 'Nurturing Qualified Reason',
      token: '{{record.values.nurturing_qualified_reason}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733d',
      label: 'syncari / Lead / Owner ID (OwnerId)',
      shortLabel: 'Owner ID',
      token: '{{record.values.OwnerId}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47334',
      label: 'syncari / Lead / Phone (Phone)',
      shortLabel: 'Phone',
      token: '{{record.values.Phone}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47338',
      label: 'syncari / Lead / Photo URL (PhotoUrl)',
      shortLabel: 'Photo URL',
      token: '{{record.values.PhotoUrl}}',
      datatype: 'url',
      group: 'Syncari',
    },
    {
      value: '60a4c95f466cec00013b8b97',
      label: 'syncari / Lead / Revenue Segment (SDR) (revenue_segment_sdr)',
      shortLabel: 'Revenue Segment (SDR)',
      token: '{{record.values.revenue_segment_sdr}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '606b554e4caebc0001379442',
      label: 'syncari / Lead / SDR Call Booked on (sdr_call_booked_on)',
      shortLabel: 'SDR Call Booked on',
      token: '{{record.values.sdr_call_booked_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '606b55744caebc0001379446',
      label: 'syncari / Lead / SDR Call Scheduled On (sdr_call_scheduled_on)',
      shortLabel: 'SDR Call Scheduled On',
      token: '{{record.values.sdr_call_scheduled_on}}',
      datatype: 'date',
      group: 'Syncari',
    },
    {
      value: '606b55af4caebc0001379454',
      label: 'syncari / Lead / SDR Call Status (sdr_call_status)',
      shortLabel: 'SDR Call Status',
      token: '{{record.values.sdr_call_status}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '608af2901e5e810001c071a5',
      label: 'syncari / Lead / Sales Account (sales_account_id)',
      shortLabel: 'Sales Account',
      token: '{{record.values.sales_account_id}}',
      datatype: 'reference',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47328',
      label: 'syncari / Lead / Salutation (Salutation)',
      shortLabel: 'Salutation',
      token: '{{record.values.Salutation}}',
      datatype: 'picklist',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732e',
      label: 'syncari / Lead / State/Province (State)',
      shortLabel: 'State/Province',
      token: '{{record.values.State}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4733a',
      label: 'syncari / Lead / Status (Status)',
      shortLabel: 'Status',
      token: '{{record.values.Status}}',
      datatype: 'picklist',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732c',
      label: 'syncari / Lead / Street (Street)',
      shortLabel: 'Street',
      token: '{{record.values.Street}}',
      datatype: 'textarea',
      group: 'Syncari',
    },
    {
      value: 'syncariEntityId',
      label: 'syncari / Lead / Syncari Id (syncariEntityId)',
      shortLabel: 'Syncari Id',
      token: '{{record.syncariEntityId}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47348',
      label: 'syncari / Lead / System Modstamp (SystemModstamp)',
      shortLabel: 'System Modstamp',
      token: '{{record.values.SystemModstamp}}',
      datatype: 'datetime',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732a',
      label: 'syncari / Lead / Title (Title)',
      shortLabel: 'Title',
      token: '{{record.values.Title}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47343',
      label: 'syncari / Lead / Unread By Owner (IsUnreadByOwner)',
      shortLabel: 'Unread By Owner',
      token: '{{record.values.IsUnreadByOwner}}',
      datatype: 'boolean',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b47337',
      label: 'syncari / Lead / Website (Website)',
      shortLabel: 'Website',
      token: '{{record.values.Website}}',
      datatype: 'url',
      group: 'Syncari',
    },
    {
      value: '604a15d81230f30001f6dae4',
      label: 'syncari / Lead / ZI - All Industries (zi_all_industries)',
      shortLabel: 'ZI - All Industries',
      token: '{{record.values.zi_all_industries}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a15ed4cdff30001162568',
      label: 'syncari / Lead / ZI - All Sub-Industries (zi_all_sub_industries)',
      shortLabel: 'ZI - All Sub-Industries',
      token: '{{record.values.zi_all_sub_industries}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a15fd1230f30001f6daea',
      label: 'syncari / Lead / ZI - Company Revenue (zi_company_revenue)',
      shortLabel: 'ZI - Company Revenue',
      token: '{{record.values.zi_company_revenue}}',
      datatype: 'integer',
      group: 'Syncari',
    },
    {
      value: '604a160f4cdff3000116256c',
      label: 'syncari / Lead / ZI - Company Revenue Range (zi_company_revenue_range)',
      shortLabel: 'ZI - Company Revenue Range',
      token: '{{record.values.zi_company_revenue_range}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a16241230f30001f6daf1',
      label: 'syncari / Lead / ZI - Industry (zi_industry)',
      shortLabel: 'ZI - Industry',
      token: '{{record.values.zi_industry}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a16374cdff30001162583',
      label: 'syncari / Lead / ZI - LinkedIn Url (zi_linkedin_url)',
      shortLabel: 'ZI - LinkedIn Url',
      token: '{{record.values.zi_linkedin_url}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a164a1230f30001f6dafb',
      label: 'syncari / Lead / ZI - Primary Industry (zi_primary_industry)',
      shortLabel: 'ZI - Primary Industry',
      token: '{{record.values.zi_primary_industry}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a16771230f30001f6db20',
      label: 'syncari / Lead / ZI - Primary Sub-Industry (zi_primary_sub_industry)',
      shortLabel: 'ZI - Primary Sub-Industry',
      token: '{{record.values.zi_primary_sub_industry}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a168b1230f30001f6db2e',
      label: 'syncari / Lead / ZI - Technologies (zi_technologies)',
      shortLabel: 'ZI - Technologies',
      token: '{{record.values.zi_technologies}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '5ff36474391cf50001b4732f',
      label: 'syncari / Lead / Zip/Postal Code (PostalCode)',
      shortLabel: 'Zip/Postal Code',
      token: '{{record.values.PostalCode}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a169e4cdff300011625b7',
      label: 'syncari / Lead / ZoomInfo Company ID (zoominfo_company_id)',
      shortLabel: 'ZoomInfo Company ID',
      token: '{{record.values.zoominfo_company_id}}',
      datatype: 'string',
      group: 'Syncari',
    },
    {
      value: '604a16ad4cdff300011625be',
      label: 'syncari / Lead / ZoomInfo Contact ID (zoominfo_contact_id)',
      shortLabel: 'ZoomInfo Contact ID',
      token: '{{record.values.zoominfo_contact_id}}',
      datatype: 'string',
      group: 'Syncari',
    },
  ],
};
