import { Entity, EntityField, EntityFieldDraftStatus, EntityFieldStatus } from 'store/entity/types';

export const entityFieldListFixture: EntityField[] = [
  {
    id: '602ffbdee9a1fdc01af29cb5',
    apiName: 'AboutUs',
    displayName: 'About Us',
    description: null,
    dataType: 'string',
    status: EntityFieldStatus.ACTIVE,
    type: null,
    tags: [],
    values: [],
    isMapped: false,
    hasChanges: false,
    draftStatus: EntityFieldDraftStatus.APPROVED,
    referenceTo: 'referenceTo',
    referenceTargetField: 'referenceTargetField',
    readOnly: false,
    required: false,
    unique: false,
    watermarkField: false,
    system: false,
    reference: false,
    multiValueField: false,
    idField: false,
  },
  {
    id: '602ffbdee9a1fdc01af29cd4',
    apiName: 'AccountSource',
    displayName: 'Account Source',
    description: null,
    dataType: 'picklist',
    status: EntityFieldStatus.ACTIVE,
    type: null,
    tags: [],
    values: [],
    isMapped: false,
    hasChanges: false,
    draftStatus: EntityFieldDraftStatus.APPROVED,
    readOnly: false,
    required: false,
    unique: false,
    watermarkField: false,
    referenceTo: 'null',
    referenceTargetField: 'null',
    system: false,
    reference: false,
    multiValueField: false,
    idField: false,
  },
  {
    id: '602ffbdee9a1fdc01af29cdc',
    apiName: 'AnnualRevenue',
    displayName: 'Annual Revenue',
    description: null,
    dataType: 'double',
    status: EntityFieldStatus.ACTIVE,
    type: null,
    tags: [],
    values: [],
    isMapped: false,
    hasChanges: false,
    draftStatus: EntityFieldDraftStatus.APPROVED,
    readOnly: false,
    required: false,
    unique: false,
    watermarkField: false,
    referenceTo: 'null',
    referenceTargetField: 'null',
    system: false,
    reference: false,
    multiValueField: false,
    idField: false,
  },
];

export const createEntityFixture = (values: Partial<Entity>): Entity => ({
  id: '5eb1120aff210932662d396b',
  apiName: 'account',
  displayName: 'Account',
  dataStoreName: 'account',
  description: null,
  subLabel: 'UNMAPPED',
  iconPath: '/assets/icons/unmapped.svg',
  pipelineStatus: 'UNMAPPED',
  type: 'standard',
  connectedTo: [],
  tags: [],
  fields: [],
  location: null,
  status: 'ACTIVE',
  draftStatus: 'APPROVED',
  createdBy: '',
  updatedBy: '',
  createdAt: '',
  updatedAt: '',
  activeFields: [],
  ...values,
});
