package com.syncari.connector.exception;

public enum ErrorCodes {
	LOGIN_ERROR,
	API_ERROR,
	NETWORK_ERROR,
	SCHEMA_ERROR,
	UNKNOWN_ERROR,
	CONNECTION_ERROR,
	NOT_SUPPORTED,
	BAD_REQUEST,
	ACCESS_DENIED,
	TOO_MANY_REQUESTS,
	ENDPOINT_DOWN,
	BAD_ENDPOINT,
	TIME_OUT,
	IO_ERROR,
	TOKEN_EXPIRED,
	UPDATE_FAILED,
	PAYLOAD_TOO_LARGE,
	DATA_NOT_FOUND,
	TABLE_NOT_FOUND,
	DATATYPE_ERROR,
	FATAL_ERROR,
	SYSTEM_ERROR,
	SQL_ERROR
}
