functions.advancedAttachRecord=/help
functions.extractDomainOnEntity=/help
functions.filter=/help
functions.case=/help
functions.avg=/help
functions.sum=/help
functions.stdDev=/help
functions.count=/help
functions.insertRecord=/help
functions.insertRecordOnField=/help
functions.firstOnEntity=/help
functions.first=/help
functions.last=/help
functions.isFalse=/help
functions.isTrue=/help
functions.advancedLookUpSyncariRecord=/help
functions.advancedLookUpSyncariRecordOnField=/help
functions.replaceOnEntity=/help
functions.setValueOnEntity=/help
functions.updateSyncariRecords=/help
functions.updateSyncariRecordsOnField=/help
functions.abs=/help
functions.floor=/help
functions.ceil=/help
functions.min=/help
functions.max=/help
functions.round=/help
functions.multiply=/help
functions.increment=/help
functions.decrement=/help
functions.plus=/help
functions.minus=/help
functions.now=/help
functions.dateFormat=/help
functions.dayOfYear=/help
functions.dayOfMonth=/help
functions.dayOfWeek=/help
functions.isBeforeNow=/help
functions.isAfterNow=/help
functions.concatenate=/help
functions.lpad=/help
functions.rpad=/help
functions.indexOf=/help
functions.extractDomain=/help
functions.extractText=/help
functions.replace=/help
functions.camelCase=/help
functions.capitalize=/help
functions.lookUpRefData=/help
functions.enrichPerson=/help
functions.enrichCompany=/help
functions.salesIntelPersonEnrich=/help
functions.salesIntelCompanyEnrich=/help
functions.setFields=/help
functions.findValue=/help
functions.decode=/help
functions.encode=/help
functions.encrypt=/help
functions.decrypt=/help
functions.uuid=/help
functions.urlEncode=/help
functions.empty=/help
functions.join=/help
functions.sort=/help
functions.split=/help
functions.length=/help
functions.lower=/help
functions.upper=/help
functions.ltrim=/help
functions.rtrim=/help
functions.trim=/help
functions.mask=/help
functions.numberFormat=/help
functions.formatPhone=/help
functions.removeNonPrintable=/help
functions.reverse=/help
functions.reverseString=/help
functions.striptags=/help
functions.substring=/help
functions.parse=/help
functions.random=/help
functions.computeRatio=/help
functions.setValue=/help
functions.addToList=/help
functions.removeFromList=/help
functions.removeDuplicates=/help
actions.sendEmail=/help
actions.addToMarketoList=/help
actions.removeFromMarketoList=/help
actions.createZendeskTicket=/help
actions.sendSlackMessage=/help
actions.addToSfdcCampaign=/help
actions.createSalesforceTask=/help
actions.convertSalesforceLead=/help
actions.addToMarketoProgram=/help
actions.requeueRecord=/help
actions.deleteExternalRecord=/help
actions.updateExternalRecord=/help
actions.createMSTeamsChannel=/help
functions.insertSyncariRecord=/help
actions.sendMSTeamsMessage=/help
