logging.level.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost
spring.data.mongodb.uri=${mongodb.uri}
spring.data.mongodb.readOnlyUri=${mongodb.readOnlyUri}

spring.cloud.gcp.project-id=${gcp.project}
spring.cloud.gcp.cf.project-id=${gcp.cf.project}
spring.cloud.gcp.credentials.encoded-key=${gcp.credentials.key}
spring.cloud.gcp.profile=development
spring.profiles.active=${spring.profiles.active}
cloud.function.endpoint=${gcp.cloud.functions.url}
spring.cloud.gcp.cfdeployer.credentials.encoded-key=${gcp.cfdeployer.credentials.key}
spring.cloud.gcp.cfexecutor.credentials.encoded-key=${gcp.cfexecutor.credentials.key}
spring.cloud.gcp.cfexecutor.sa.email=${gcp.cfexecutor.sa.email}

# GCP pub/sub subscriber executor threads default is 4, we scale it up to 16.
spring.cloud.gcp.pubsub.subscriber.executor-threads=48
spring.cloud.gcp.pubsub.emulator-host=${spring.cloud.gcp.pubsub.emulator-host:}

event.log.topic.name=${eventlog.topic.name}
event.log.subscription.name=${eventlog.subscription.name}
generic.topic.name=${generic.topic.name}
generic.subscription.name=${generic.subscription.name}
webhook.topic.name=${webhook.topic.name}
webhook.subscription.name=${webhook.subscription.name}
error.notification.topic.name=${error.notification.topic.name}
error.notification.subscription.name=${error.notification.subscription.name}
dfi.result.notification.topic.name=${dfi.result.notification.topic.name}
dfi.result.notification.subscription.name=${dfi.result.notification.subscription.name}
appconfig.api.server.host=${api.server.host}
appconfig.spectrum.server.host=${spectrum.server.host}
#Bump up the header size to include very large headers coming in from OAuth redirects
server.max-http-header-size=65536
notification.pd.email=
mail.smtp.port=${mail.port}
mail.smtp.host=${mail.host}
mail.smtp.timeout=60000
mail.smtp.connectiontimeout=60000
mail.smtp.writetimeout=60000
mail.sender.username=${mail.username}
mail.sender.from-email=${mail.sender.from-email:team@nextedge.ai}
#mail.sender.from-for-error-email=prod-errors@syncari.com
mail.sender.from-for-error-email=${mail.from.for.error}
mail.sender.password=${mail.password}

mail.sender.from-plg-email=${mail.plg.username}

google.cloud.cdn.host=${syncari.asset.cdn}
zendesk.shared.secret=${zendesk.shared.secret}
zendesk.sso.secret=${zendesk.sso.secret}
zendesk.support.url=${zendesk.support.url}
zendesk.support.url.alias=${zendesk.support.url.alias}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

gcs.bucket.name=${gcs.bucket.name}
gcs.cf.bucket.name=${gcs.cf.bucket.name}

clearbit.api.key=${clearbit.api.key}
syncari.slack.client.id=${syncari.slack.client.id}
syncari.slack.client.secret=${syncari.slack.client.secret}
syncari.slack.synapse.signing.secret=${syncari.slack.synapse.signing.secret}
syncari.datastore.host=${syncari.datastore.host}
syncari.datastore.user=${syncari.datastore.user}
syncari.datastore.password=${syncari.datastore.password}
syncari.datastore.cert=${syncari.datastore.cert}

syncari.salesloft.client.id=${syncari.salesloft.client.id}
syncari.salesloft.client.secret=${syncari.salesloft.client.secret}

syncari.hubspot.client.id=${syncari.hubspot.client.id}
syncari.hubspot.client.secret=${syncari.hubspot.client.secret}

syncari.gsuite.client.id=${syncari.gsuite.client.id}
syncari.gsuite.client.secret=${syncari.gsuite.client.secret}

environment.name=${environment.name}
syncari.salesintel.apikey=${syncari.salesintel.apikey}
workramp.internal.privateKey=${workramp.internal.privateKey}
workramp.internal.certificate=${workramp.internal.certificate}

workramp.academies.privateKey=${workramp.academies.privateKey}
workramp.academies.certificate=${workramp.academies.certificate}

workramp.sp.saml.internal.metadata=${workramp.sp.saml.internal.metadata}
workramp.sp.saml.academies.metadata=${workramp.sp.saml.academies.metadata}

spring.redis.host=${redis.host}
spring.redis.port=${redis.port}
spring.redis.user=
spring.redis.password=${redis.password}
spring.redis.timeout=5000

spring.newredis.host=${new.redis.host}
spring.newredis.port=${new.redis.port}
spring.newredis.user=
spring.newredis.password=${new.redis.password}


entitycache.redis.host=${entitycache.redis.db.host}
entitycache.redis.port=${entitycache.redis.db.port:6379}
entitycache.redis.user=
entitycache.redis.password=${entitycache.redis.db.password}

proxy.enabled=${proxy.enabled}
proxy.host=${proxy.host}
proxy.port=${proxy.port}

syncari.jwt.security.secret=${syncari.jwt.security.secret}
syncari.env.name=${syncari.env.name}
webhook.server.host=${webhook.server.host}
webhook.karibu.server.host=${webhook.karibu.server.host}

cf.vpc.connector=${cf.vpc.connector}

gcp.ts.bgsa.credentials.key=${gcp.ts.bgsa.credentials.key}

permit.io.api.key=${permit.io.api.key}
permit.io.pdp.endpoint=${permit.io.pdp.endpoint}
