<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.syncari</groupId>
	<artifactId>backend</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>11</java.version>
		<jedis.version>4.4.0-m1</jedis.version>
        <revision>DEV-SNAPSHOT</revision>
		<gson.version>2.10.1</gson.version>
		<json-path.version>2.9.0</json-path.version>
    </properties>
	<!--Common Dependencies -->
	<dependencies>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.10.19</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<modules>
        <module>utils</module>
        <module>connector</module>
        <module>core</module>
		<module>restutils</module>
        <module>dbm</module>
        <module>visions</module>
        <module>viper</module>
        <module>arcade</module>
        <module>karibu</module>
	</modules>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*</include>
				</includes>
			</testResource>
		</testResources>
		<plugins>
			<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>flatten-maven-plugin</artifactId>
			<version>1.2.7</version>
			<configuration>
				<updatePomFile>true</updatePomFile>
				<flattenMode>resolveCiFriendliesOnly</flattenMode>
			</configuration>
			<executions>
				<execution>
				<id>flatten</id>
				<phase>process-resources</phase>
				<goals>
					<goal>flatten</goal>
				</goals>
				</execution>
				<execution>
				<id>flatten.clean</id>
				<phase>clean</phase>
				<goals>
					<goal>clean</goal>
				</goals>
				</execution>
			</executions>
			</plugin>
		</plugins>
	</build>
</project>
